<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Regulamento</title>
    </head>
    <body>
<p>ÍNDICE</p>
<p> I- APRESENTAÇÃO E CONDIÇÕES GERAIS  <br />
  II- ADMINISTRAÇÃO<br />
III- FINALIDADE DA PROTEÇÃO DO (S) VEÍCULOS  <br />
IV- BENS PROTEGIDOS  <br />
V- VIGÊNCIA  <br />
VI- ACEITAÇÃO E VIGÊNCIA DA PROTEÇÃO DE ACIDENTES EM VEÍCULOS  <br />
VI.1-    NÃO  ACEITAÇÃO POR PARTE DA DIRETORIA  <br />
VI.2-    RENOVAÇÃO  <br />
VII -    PATRIMÔNIO/ CAPITAL  <br />
VIII -  TAXA DE FILIAÇÃO A PROTEÇÃO DE ACIDENTES EM  VEÍCULOS  “TAXA DE ADESÃO”  <br />
VIII.1- FINALIDADE  <br />
VIII.2- CESSÃO DE DIREITOS/TRANSFERÊNCIA  <br />
VIII.3- VALORES PRÉ-FIXADOS  <br />
IX-       MENSALIDADES  <br />
IX.1-    RESTITUIÇÃO  <br />
X-       RATEIO MENSAL  <br />
X.1-      RATEIO MENSAL PELO NÚMERO DE COTAS<br />
X.2-      TABELA DE RATEIO POR COTAS<br />
X.3-     VENCIMENTO MENSAL  <br />
X.4-     TOLERÂNCIA/MULTA  <br />
X.5-     SUSPENSÃO DA PROTEÇÃO DE ACIDENTES EM  VEÍCULOS  <br />
X.5-A   PELO DESCUMPRIMENTO DE PAGAMENTO  <br />
X.5-B   POR INTERESSE PARTICULAR DO ASSOCIADO  <br />
X.6 –     CANCELAMENTO DA TAXA DE ADESÃO  <br />
X.6-A    PELO DESCUMPRIMENTO  DE PAGAMENTO  <br />
X.6-B    POR INTERESSE PARTICULAR DO ASSOCIADO  <br />
X.6-C    POR NEGLIGENCIA  OU IMPRUDÊNCIA DO ASSOCIADO  <br />
X.7 –     RESTABELECIMENTO DA PROTEÇÃO DE ACIDENTES EM VEÍCULOS  <br />
X.8 –     SUBSTITUIÇÃO DE VEÍCULO (S)  <br />
X.9 –     RESTITUIÇÃO  <br />
XI -    PROTEÇÃO DE ACIDENTES EM VEÍCULOS  <br />
XI.1 - PROTEÇÃO BÁSICA  <br />
XII-    ABRANGENCIA DA PROTEÇÃO DE ACIDENTES EM VEÍCULOS  <br />
XIII-   TETO MÁXIMO  DE INDENIZAÇÃO PATRIMONIAL (LIMITE  DE RESPONSABILIDADE) <br />
XIV-         INDENIZAÇÃO PATRIMONIAL  <br />
XIV.1 -     INDENIZAÇÃO INTEGRAL DO PATRIMÔNIO  <br />
XIV.1-A -  PERDA INTEGRAL EM DECORRÊNCIA DE COLISÃO  <br />
XIV.1-B-   PERDA INTEGRAL EM DECORRÊNCIA DE  ROUBO  <br />
XIV.2 - CÁLCULO DO VALOR INTEGRAL CAMINHÃO  <br />
XIV.3 - CALCULO DO VALOR INTEGRAL  IMPLEMENTOS, SEMI-REBOQUE  <br />
XIV.4 -    INDENIZAÇÃO DANOS MATERIAIS PARCIAIS  <br />
XV-         PARTICIPAÇÃO OBRIGATÓRIA DO ASSOCIADO EM ACIDENTES   CONTRIBUIÇÃO OBRIGATORIA  <br />
XV.1 -  VALOR  <br />
XV.2 -  CONDIÇÃO DE PAGAMENTO <br />
  XVI -    OBRIGAÇÕES DO ASSOCIADO  <br />
  XVI.1-   EM CASO DE ACIDENTE PROTEÇÃO NESTE REGULAMENTO  <br />
  XVII -  VERIFICAÇÃO <br />
  XVIII - OS RISCOS E PREJUÍZOS QUE A PROTEÇÃO DE ACIDENTES EM VEÍCULOS - NÃO INDENIZA  <br />
  XIX-     RESPONSABILIDADE CIVIL FACULTATIVA DE VEÍCULO  <br />
  XX -     DANOS MATERIAIS A TERCEIROS  <br />
  XXI-     DANOS CORPORAIS A TERCEIROS  <br />
  XXII-    DANOS MORAIS A TERCEIROS  <br />
  XXIII-   PROTEÇÃO ADICIONAIS  <br />
  XXIV-   ACIDENTES PESSOAIS DE PASSAGEIROS  <br />
  XXV-    ASSISTÊNCIA 24 HORAS  <br />
  XXVI-   OCORRÊNCIAS QUE CANCELAM A PROTEÇÃO DE ACIDENTES EM VEÍCULOS  <br />
  XXVII-  OCORRÊNCIAS QUE TORNAM A PROTEÇÃO DE ACIDENTES EM VEÍCULOS- SEM EFEITO <br />
  XXVIII- DAS SOBRAS DO CAMINHÃO/SEMI-REBOQUE/IMPLEMENTOS  <br />
  XXIX-   PROCEDIMENTOS DE DOCUMENTAÇÃO EM CASO DE ACIDENTES PROTEGIDOS PELA - PROTEÇÃO DE ACIDENTES EM VEÍCULOS<br />
XXIX.1- DOCUMENTAÇÃO NECESSÁRIA  <br />
XXX –  ALIENAÇÃO OU RESERVA DE DOMÍNIO  <br />
XXXI – SUB-ROGAÇÃO DE DIREITOS  <br />
XXXII-  FORO  <br />
XXXIII- GLOSSÁRIO<br />
<br />
  PROTEÇÃO DE PATRIMÔNIO REGULAMENTO DO GRUPO DE ASSESSORIA DE ACIDENTES <br />
  O presente documento tem escopo regulamentar à proteção do patrimônio dos associados da Associação São Paulo de Caminhoneiros, segundo critério de rateio dos prejuízos decorrentes de acidentes, roubos, colisão,entre os participantes  da associação, sem qualquer fim lucrativo ou econômico, em consonância com os permissivos legais contidos no artigo 54 do Código Civil e artigo 5º, XVII, da Constituição federal. <br />
  I - APRESENTAÇÃO E CONDIÇÕES GERAIS: Parágrafo Primeiro. A Associação São Paulo de Caminhoneiros, é uma sociedade civil sem fins lucrativos; político, partidário ou religioso; com duração de prazo indeterminado e ilimitado   número   de   associados,   dotada   de   personalidade jurídica, constituída na forma de Associação com compromisso e ética e de respeito a todos com quem nos relacionamos, sendo a união de pessoas com fins comuns, não devendo ser confundida em hipótese nenhuma com sociedade empresarial mercantil e de exploração do ramo de seguro, já que a associação não é seguradora. Parágrafo Segundo. A . é feita da confiança dos nossos associados, da sociedade e na confiança em nossas práticas. Trabalhamos com transparência e nosso objetivo primordial é conferir proteção e segurança aos caminhões, carretas e implementos de nossos associados, simplesmente chamados de veículos. <br />
  Parágrafo Terceiro. A assessoria de acidentes tem regulamentação própria,  observados  sempre  o  Estatuto  e  Regimento  interno  da Associação São Paulo de Caminhoneiros. Parágrafo Quarto. Esta versão do regulamento do grupo de assessoria de acidentes substitui qualquer outra que por ventura anteriormente tenha sido registrada. Esta <br />
edição foi aprovada em reunião   específica,   pelos   membros   diretores   da   Associação São Paulo de Caminhoneiros e registrada em ata. Parágrafo Quinto.  Os valores referentes às despesas administrativas e todos os custos para a proteção dos veículos serão pagos pelos associados, que efetivamente tenham seus veículos cadastrados nesta modalidade, através da repartição entre os associados de eventuais prejuízos materiais sofridos nestes bens em função do exercício da atividade profissional de transportadores rodoviários de cargas. A repartição desses valores será feita proporcionalmente ao número de cotas por veículos ativos cadastrados. Parágrafo Sexto. O associado não tem qualquer direito a ressarcimento quando da suspensão ou cancelamento de um veículo cadastrado nesta modalidade, seja qual for o motivo. Parágrafo Sétimo. A Associação São Paulo de Caminhoneiros constitui uma individualidade diferente dos seus associados, não existindo direitos e deveres recíprocos entre esses e a associação e nem entre os associados. A Associação São Paulo de Caminhoneiros não terá ainda, qualquer responsabilidade perante terceiros, em caso de danos materiais, corporais e morais causados por um Associado ou veículo(s) cadastrado(s) nesta modalidade. </p>
<p>II – ADMINISTRAÇÃO: Parágrafo Primeiro. A administração da Assessoria de Acidentes será  formada  por  um  Conselho,  composto  por três membros, escolhidos pelo Conselho Fundador, através de votação. <br />
  Parágrafo Segundo. As decisões do Conselho de Administração da Assessoria de Acidentes, obedecendo às condições descritas nestes regulamento. Parágrafo Terceiro. O associado que optar pela proteção da Associação São Paulo de Caminhoneiros não poderá utilizar os benefícios de proteção de veículos em outras associações, sob pena de perda da proteção ora convencionada. Parágrafo Quarto. As questões omissas ou polêmicas serão levadas para a diretoria da Associação São Paulo de Caminhoneiros, que decidirá, por votação da maioria simples dos seus membros. Parágrafo Quinto. Os casos omissos no presente regulamento poderão ser decididos por Assembléia Geral convocada para este fim. </p>
<p>III – FINALIDADE DA PROTEÇÃO DO(S) VEÍCULO(S): Parágrafo Primeiro. A reposição, indenização patrimonial ou reparação dos caminhões, semi-reboques, e implementos dos Associados, roubo ou destruído total ou parcialmente por acidente, obedecendo às condições descritas neste regulamento. Parágrafo Segundo. Cumprir todas as normas estabelecidas no estatuto social e neste regulamento, bem como outras a serem expedidas formalmente pela diretoria executiva. </p>
<p>IV – BENS PROTEGIDOS: Parágrafo Primeiro. Serão protegidos pela Associação São Paulo de Caminhoneiros todos os caminhões, semi-reboques e implementos cadastrados pelos associados de sua propriedade ou sob sua responsabilidade, nos termos do presente regulamento. O(s) veículo(s) cadastrado(s) será(ão) reconhecido(s) através  de documentações específicas, foto(s), placa(s)  e decalque(s) dos números de chassi. Toda alteração deverá ser comunicada à Associação São Paulo de Caminhoneiros. Caso não seja feita a comunicação o(s) veículos(s) não estará(ão) protegido(s). Parágrafo Segundo. O veículo cadastrado junto à Associação São Paulo de Caminhoneiros não poderá ser protegido por seguros particulares, sob pena de o associado perder seus direitos em relação aos benefícios oferecidos pela Associação e ser excluídos de seu corpo social, salvo no caso de seguro de danos materiais e corporais a terceiros, tendo em vista que a . Associação dos Caminhoneiros do Estado de São <br />
  Paulo não assume qualquer indenização a terceiros. </p>
<p>V – VIGÊNCIA: Parágrafo Único. A vigência desta modalidade está diretamente ligada e limitada à duração da Associação São Paulo de Caminhoneiros.</p>
<p> <br />
  VI – ACEITAÇÃO E VIGÊNCIA DA PROTEÇÃO DE ACIDENTES EM VEÍCULOS: Parágrafo Primeiro. Caso o associado faça a opção de PROTEÇÃO DE ACIDENTES EM VEÍCULOS modalidade oferecida pela Associação São Paulo de Caminhoneiros, o mesmo preencherá um cadastro através de um termo especifico e individual para cada caminhão, semi-reboque e implemento que será levado à Diretoria da Associação São Paulo de Caminhoneiros para aprovação. Aprovada a inclusão, o associado que deverá efetuar o pagamento da TAXA DE FILIAÇÃO A PROTEÇÃO DE ACIDENTES EM VEÍCULOS “TAXA DE ADESÃO”, prevista no item VIII e posteriormente cada veículo deverá ser encaminhado a uma verificação, pré-agendada na sede administrativa da Associação São Paulo de Caminhoneiros, ou fora da mesma. Cumprindo todo esse processo e comprovado o pagamento da taxa específica, o(s) patrimônio(s) estará(ão) automaticamente incluso, a partir da 00:00h do dia seguinte, na modalidade PROTEÇÃO DE ACIDENTES EM VEÍCULOS para os associados e o mesmo ciente dos deveres e obrigações assumidas a partir desta  data discriminadas neste regulamento. Em hipótese alguma o veículo estará protegido se não for feita verificação do mesmo, salvo no caso de ser dada a proteção a esse patrimônio mediante a apresentação da copia da nota fiscal do veículo. <br />
  Parágrafo Segundo. O período mínimo de permanência dos Associados nesta modalidade é de 3 (três) meses a partir do ingresso no corpo social e caso o associado venha usufruir o benefício de reparação de veículo pela Associação, sua exclusão ficará condicionada também a quitação de todas as suas obrigações junto à Associação São Paulo de Caminhoneiros até a data de sua saída, além de um novo período mínimo de 12 (doze) meses de permanência a partir do recebimento desses benefício. Parágrafo Terceiro. O associado que se desligar do corpo social por motivo  pessoal,  antes  de  completado  o  período  mínimo  de associação, desde que cumpridas todas suas obrigações em relação à Associação São Paulo de Caminhoneiros, pagará uma multa correspondente ao valor da média de repartição de prejuízos dos 03 (três) últimos meses multiplicada pelo número de meses faltantes para o término de seu período mínimo de associação. No caso de inadimplência, poderá o ex-associado ter o nome enviado aos órgãos de proteção ao crédito, bem como, ao Cartório de Protesto de Títulos e Documentos.</p>
<p><br />
  VI. 1 – NÃO ACEITAÇÃO POR PARTE DA DIRETORIA: Parágrafo Único. Caso não seja aceito pela diretoria a inclusão do(s)  veículo(s) nesta modalidade, a Associação São Paulo de Caminhoneiros terá  15 (quinze) dias para se manifestar através  de carta registrada para o associado responsável. Os valores pagos, única e exclusivamente nesta situação, serão devolvidos ao associado. <br />
  VI.2 – RENOVAÇÃO: Parágrafo Único. A renovação da proteção do(s) se dará de forma automática. Anualmente será necessária uma nova verificação do(s) veículo(s) e implemento(s) cadastrados. Cabendo à Associação São Paulo de Caminhoneiros informar antecipadamente ao associado que terá um prazo de até 30 (trinta) dias para fazê-la em sua sede.</p>
<p><br />
  VII – PATRIMÔNIO / CAPITAL: Parágrafo Primeiro. A Associação São Paulo de Caminhoneiros possui patrimônio próprio, oriundo de contribuições específicas dos associados ou parceiros, colaboradores destinados para movimentação financeira da entidade. Parágrafo Segundo. Qualquer caminhão, semi-reboque e implemento, roubado já indenizado e rateado, que por ventura vier a ser recuperado em qualquer condição física que seja, fará parte do patrimônio desta entidade, cabendo a diretoria da Associação São Paulo de Caminhoneiros, a qualquer momento, definir a venda ou destino final do mesmo, incorporando ao caixa específico desta Associação os valores apurados. Critério este válido também para os salvados “item XXVIII”, provenientes de danos indenizados pela Associação São Paulo de Caminhoneiros. Parágrafo Terceiro. Os rendimentos especificados de aplicações financeiras e deduzidos os impostos previstos também serão acrescidos ao patrimônio desta entidade. VIII -  TAXA DE FILIAÇÃO A PROTEÇÃO DE VEÍCULOS “TAXA DE ADESÃO”.</p>
<p><br />
  VIII 1. FINALIDADE Parágrafo Único. Sobre a TAXA DE ADESÃO PROTEÇÃO DE ACIDENTES EM VEÍCULOS “ TAXA DE ADESÃO”,  esta contribuição servirá para formação de um caixa específico a esta modalidade, será usado para movimentação financeira e na eventualidade pagamento de, permanecera a disposição em conta corrente ou em aplicação de titularidade desta entidade, administrada  pela diretoria da Associação São Paulo de Caminhoneiros.</p>
<p><br />
  VIII. 2 – CESSÃO DE DIREITOS / TRANSFERÊNCIA: Parágrafo Único. A “TAXA DE ADESÃO” quando adquirida não poderá ser transferida, negociada ou cedido direito de uso a outros, a mesma uma vez adquirida será pessoal e intransferível. </p>
<p><br />
  VIII. 3 VALORES PRÉ-FIXADOS: Parágrafo Primeiro. Ficam estabelecidos os seguintes valores para TAXA DE ADESÃO A PROTEÇÃO DE ACIDENTES EM VEÍCULOS “TAXA DE ADESÃO”. TABELA 1.1 VEÍCULO VALOR DA TAXA DE ADESÃO CAVALO ou CAMINHÃO  R$ 600,00 <br />
  SEMI-REBOQUE (por placa) R$    300,00 IMPLEMENTOS R$    300,00 Parágrafo Segundo. Os valores citados na tabela 1.1 a critério da Diretoria da Associação São Paulo de Caminhoneiros, poderão sofrer alterações a partir de 200 (duzentos) veículos cadastrados. Parágrafo Terceiro. O associado não tem qualquer direito  à restituição  de valores pagos, referente à “TAXA DE ADESÃO” quando da suspensão ou cancelamento de um veículo cadastrado nesta modalidade seja qual for o motivo. Salvo “item VI. 1”. Parágrafo Quarto. Por qualquer motivo que se suspenda ou cancele a “TAXA DE ADESÃO” automaticamente fica o veículo ou implemento sem    proteção.    Ficando     a     .     Associação     dos Caminhoneiros do Estado de São Paulo livre de responsabilidade em caso de acidentes, roubos ou colisão , nessas situações.</p>
<p> <br />
  IX – MENSALIDADE: Parágrafo Primeiro. Será cobrado de todo associado, mensalmente, através de boleto bancário ou outra forma que venha a ser estabelecida pela diretoria executiva, uma mensalidade corres <br />
  pondente a 30% (trinta por cento sobre o salário mínimo) por placa cadastrada junto à Associação São Paulo de Caminhoneiros, para os custos administrativos. Este valor será administrado pela DIRETORIA EXECUTIVA da . <br />
  Associação São Paulo, aplicando os referidos recursos na manutenção das despesas administrativas da Associação. Parágrafo Segundo. Para os casos de indenizações ou reposições do patrimônio dos associados, será feito um rateio sobre o valor das despesas, sempre respeitando a quantidade de quotas. Parágrafo Terceiro. No caso do valor cobrado a título de mensalidade ser superior às despesas o valor excedente será incorporado ao caixa formado pela TAXA DE ADESÃO A PROTEÇÃO DE ACIDENTES EM VEÍCULOS “TAXA DE ADESÃO” e usado para a movimentação financeira administrada pela diretoria da Associação São Paulo de Caminhoneiros. IX.1 – RESTITUIÇÃO: Parágrafo Único. O associado não tem qualquer direito à restituição de valores pagos, referente à taxa de adesão ou mensalidade, quando da suspensão ou cancelamento de um veículo cadastrado nesta modalidade, seja qual for o motivo.</p>
<p><br />
  X – RATEIO MENSAL: <br />
  X.1 – RATEIO MENSAL PELO NÚMERO DE COTAS: Parágrafo Único. Depois de apuradas as despesas mensais e indenizações patrimoniais dos acidentes e deste valor ser abatido o total das mensalidades pagas pelos associados “ITEM IX” o valor restante será dividido pelo número de cotas total do grupo até o fechamento do mês. Cada associado pagará o valor proporcional ao número de cotas por veículo protegido respeitando sempre a tabela de RATEIO  POR COTAS (tabela X.2). <br />
  X.2 – TABELA DE RATEIO POR COTAS: <br />
  VALOR DO VEÍCULO Nº DE COTAS DE R$           0,00  A R$    50.000,00 1 DE R$  50.001,00 A R$  100.000,00 2 DE R$ 100.001,00 A R$ 150.000,00 3 DE R$ 150.001,00 A R$ 200.000,00 4 DE R$ 200.001,00 A R$ 250.000,00 5 ATÉ        R$ 300.000,00 6 SEMI-REBOQUE     R$   50.000,00 1 IMPLEMENTOS      R$    50.000,00 1 OBS.: A TABELA ACIMA SERÁ UTILIZADA COMO REFERÊNCIA DO NÚMERO DE COTAS PARA CADA VEÍCULO CADASTRADO JUNTO A Associação São Paulo de Caminhoneiros. O ASSOCIADO RECEBERÁ UM RELATÓRIO COM O NÚMERO DE COTAS INDIVIDUAIS POR VEÍCULO CADASTRADO JUNTO A Associação São Paulo de Caminhoneiros. <br />
  X. 3 – VENCIMENTO MENSAL: Parágrafo Único. O vencimento do boleto mensal referente à mensalidade e ao “RATEIO” mensal será todo o dia 15 (quinze) de cada mês ou primeiro dia útil subsequente). <br />
  X.4 – TOLERÂNCIA / MULTA Parágrafo Único. Informamos que não existe prazo de tolerância para pagamento após a data de vencimento, ou seja, após a data de vencimento se não houver a quitação do boleto, o veículo cadastrado estará descoberto e o associado poderá ter seu nome incluso no serviço de proteção ao crédito - SPC. X.5 - SUSPENSÃO DA PROTEÇÃO DE ACIDENTES EM VEÍCULOS: <br />
  X.5 – “A” – PELO DESCUMPRIMENTO DE PAGAMENTO: Parágrafo Único. A falta de pagamento do boleto, previsto no “item X.3”, implicará  na suspensão automática  da proteção do(s) veículo(s) cadastrado(s) nesta modalidade. Nesta condição o veículo suspenso continuará participando dos rateios mensais pelo número de cota. <br />
  aberto neste caso será cancelada a “TAXA DE ADESÃO”  e todos os vínculos para ambas as partes previstos neste regulamento serão cancelados a partir da data de solicitação do cancelamento. <br />
  X.6 – “C” – POR NEGLIGENCIA OU IMPRUDENCIA DO ASSOCIADO: Parágrafo Único. A Diretoria poderá advertir e em casos extremos e de reincidências cancelar a cota de adesão e a proteção dos veículos e implementos nos casos de: a) Negligência do associado, arrendatário ou cessionário na utilização; b) Acidentes ocasionados pela inobservância de disposições legais como dirigir sem possuir carteira de habilitação ou estar com a mesma suspensa ou vencida, ou ainda, não ter habilitação adequada conforme a categoria do veículo, bem como, utilizar inadequadamente o veículo com relação à c) lotação de passageiros, excesso de peso e acondicionamento de carga transportada; d) A proteção não cobrirá os danos sofridos em agregados e carrocerias, ressalvados aqueles agregados que constam especificados   na   proposta   de   adesão   e   conjunto e) cadastrado nesta modalidade. E a cobertura de carretas caçambão(caçamba) ou carretas basculante, não terão f) cobertura se estiverem acima da capacidade do fabricante, portanto, é necessário apresentar os seguintes documentos; - Nota Fiscal ou Romaneio de Trasnsporte - Conhecimento de Trasnporte. - Ticheets de Balança (informando o peso transportado). - Boletim de Ocorrência do Acidente. - Cópia da Carteira de Habilitação do Condutor no Ato do Acidente. g) Atos praticados sob efeito de bebidas alcoólicas ou tóxicas; h) Ato reconhecidamente perigoso que não seja motivado por necessidade justificada; i) Submeter o veículo cadastrado a riscos desnecessários ou atos imprudente, como excesso de velocidade, manutenção preventiva irregular, pneus visivelmente desgastados ou  carecas,  ausência  ou  falta  de  funcionamento  do j) equipamento obrigatório tacógrafo e se necessário fazer teste de embriaguez (bafômetro) ou exame de sangue para verificar os níveis de álcool no sangue. <br />
  A Associação São Paulo de Caminhoneiros, poderá, a seu critério, restabelecer a PROTEÇÃO DE ACIDENTES EM VEÍCULOS, caso o débito do Associado seja quitado dentro dos prazos determinados e os veículos sejam submetidos a uma nova verificação ou vistoria pré-agendada na sede administrativa da Associação São Paulo de Caminhoneiros. </p>
<p>X.5 – “B” – POR INTERESSE PARTICULAR DO ASSOCIADO: Parágrafo Único. O Associado e ou representante legal terá o direito de suspender a proteção do(s) veículo(s) cadastrado(s) nesta modalidade através de termo formal específico. Para o Associado ter este direito, a cota referida deverá estar com os pagamentos em dia e não poderá a mesma ter algum tipo de acidente em aberto e o associado ciente do compromisso de pagamento do rateio dos acidentes por venturos já ocorridos até a data da suspensão. Neste caso o associado após o último pagamento terá um prazo máximo de 06 (seis) meses corridos para recadastrar outro na referida proteção suspensa. Com isenção da taxa da “COTA DE ADESÃO”, prevista no “item VIII” deste regulamento. </p>
<p>X.6 – CANCELAMENTO DA TAXA DE ADESÃO </p>
<p>X.6 – “A” – PELO DESCUMPRIMENTO  DE PAGAMENTO: Parágrafo único. Após 60 (sessenta) dias inadimplente o associado terá sua cota de adesão automaticamente cancelada. A Associação São Paulo de Caminhoneiros poderá, a seu critério, restabelecer a PROTEÇÃO DE ACIDENTES EM VEÍCULOS, para que isto  ocorra será necessário que o associado pague novamente a TAXA DE ADESÃO “item VIII” e conclua todo processo de inclusão semelhante à de um novo associado. X.6 – “B” – POR INTERESSE PARTICULAR DO ASSOCIADO Parágrafo único. O Associado e ou representante legal terá o direito de cancelar sua cota de adesão a seu critério desde que cumprido o período mínimo de associação através de solicitação formal a .. Nesta condição o associado deverá estar em dia com os pagamentos e não poderá o mesmo ter algum tipo de acidente em a) b)c) d) e) <br />
  X.7 -  RESTABELECIMENTO DA PROTEÇÃO  DE ACIDENTES EM VEÍCULOS: Parágrafo Único. A Associação São Paulo de Caminhoneiros poderá, a seu critério, restabelecer a PROTEÇÃO DE ACIDENTES EM VEÍCULOS, caso o débito do associado seja quitado dentro dos prazos determinados e os veículos sejam submetidos a uma nova verificação pré-agendada na sede administrativa da Associação São Paulo de Caminhoneiros. Esta não se responsabilizará por qualquer acidente ocorrido naquele período que o associado inadimplente ficou ausente e sem proteção. <br />
  X.8 – SUBSTITUIÇÃO DE VEÍCULO (S): Parágrafo Único. O associado ou representante legal terá o direito de  substituir  (através  de  formulário  especifico)  o(s)  veículos(s) cadastrado(s)  nesta modalidade  desde que a referida mensalidade esteja com os pagamentos em dia e não  poderá a mesma ter algum tipo  de acidente em aberto. Sendo assim, mediante  verificação, na sede da Associação São Paulo de Caminhoneirosdo(s) veículo(s) substituto(s)  e  o  associado  ciente do compromisso do pagamento da mensalidade e do rateio proporcional a do veículo cadastrado (SUBSTITUTO).</p>
<p> <br />
  X.9 RESTITUIÇÃO: Parágrafo Único. O Associado não tem qualquer  direito à restituição  de  valores  pagos,  referente  ao  rateio quando  da  suspensão ou cancelamento de um veículo cadastrado nesta modalidade, seja qual for o motivo. </p>
<p>XI  – PROTEÇÃO DE ACIDENTES EM VEÍCULOS: Parágrafo Primeiro. EM HIPÓTESE ALGUMA, A Associação São Paulo de Caminhoneiros ASSUME QUALQUER TIPO DE RESPONSABILIDADE DE INDENIZAÇÃO PERANTE TERCEIROS ENVOLVIDOS, FICANDO A CRITÉRIO E RESPONSABILIDADE DO ASSOCIADO OU PROPRIETÁRIO LEGAL DO VEÍCULO A CONTRATAÇÃO DESTA MODALIDADE ATRAVÉS DE OUTROS MEIOS ESPECIFICOS DESTINADOS A TAL. <br />
  Parágrafo Segundo. Riscos protegidos somente nas regiões Norte, Nordeste e Centro-Oeste do Brasil.</p>
<p>. <br />
  XI.1- Proteções Básicas: COLISÃO, INCÊNDIO (meditante acidente),  ROUBO: Parágrafo Primeiro. Colisão: danos materiais causados ao veículo por colisão, capotamento, abalroamento, queda de objetos externos sobre o veículo. Os pneus câmaras de ar do caminhão, estão desde que não afetados isoladamente nas circunstâncias  descritas acima e observada a depreciação de uso constatada. Parágrafo Segundo.  Colisão e Incêndio (mediante acidente): Danos materiais causados acidentalmente por colisão, só serão ressarcidos após inquérito policial e perícia, constando que o colisão  foi em decorrência do acidente. Neste  caso  a  .  Associação  dos  Caminhoneiros  do Estado de São Paulo cobrirá 80% do bem protegido. Parágrafo Terceiro. Roubo Qualificado ou Não do Veículo: Instaurado inquérito policial e após sua conclusão e toda documentação entregue na sede da ., a Associação tem 60 dias para indenizar o associado, no qual terá direito a 80% do bem protegido. Parágrafo Quarto. Roubo do Veículo: Instaurado inquérito policial e após sua conclusão e toda documentação entregue na sede da ., a Associação tem 60 dias para indenizar o associado, no qual terá direito a 80% do bem protegido. </p>
<p>XII -  ABRANGÊNCIAS DA PROTEÇÃO DE ACIDENTES EM VEÍCULOS:<br />
A) Caminhão: COLISÃO, INCÊNDIO (meditante acidente), ROUBO. - Os acessórios do caminhão não estão acobertados.         - Não há proteção para pneus. <br />
B) Semi-reboque COLISÃO, INCÊNDIO (meditante acidente), ROUBO. - Obs.: Este só terá proteção em caso de colisão, colisão , roubo quando o fato se fizer em <br />
  conjunto a um caminhão acoplado, ambos inclusos  e aptos nesta  modalidade, nos termos do presente regulamento. Não há proteção para pneus. <br />
  C) Implementos:  COLISÃO, INCÊNDIO (meditante acidente), ROUBO E . - obs.: Os implementos  e semireboques, no caso de Roubo  só terão proteção quando o fato se fizer em conjunto a um caminhão e ambos inclusos e aptos nesta modalidade. </p>
<p><br />
  XIII – TETO MÁXIMO DE INDENIZAÇÃO PATRIMONIAL (LIMITE DE RESPONSABILIDADE): <br />
  a) – CAMINHÃO: o valor de indenização patrimonial possui teto máximo de R$ 300.000,00 (trezentos mil reais) para cada cavalo ou caminhão cadastrado, respeitando  sempre a tabela FIPE do veículo. <br />
  b) – SEMI-REBOQUE: O valor de proteção patrimonial possui teto máximo de R$ 50.000,00 (cinqüenta mil reais) para o (s)  semi-reboque (s), por placa desde que estejam cadastrados. OBS. bitrem ou rodotrem são duas placas. <br />
  c) – IMPLEMENTOS: o valor de proteção patrimonial de teto máximo do implemento é de R$ 50.000,00 (cinquenta mil reais), tanto para: colisão, roubo . Parágrafo Único. O valor máximo para pagamento é de R$ 350.000,00 (trezentos e cinquenta mil reais), para todo conjunto cadastrado.</p>
<p> <br />
  XIV – INDENIZAÇÃO PATRIMONIAL: Parágrafo Primeiro. Valor pago pela Associação São Paulo de Caminhoneiros, após comprovação do acidente a título de ressarcimento de danos, limitada ao valor do teto máximo de indenização, patrimonial estabelecido para cada tipo de veículo ou implemento com a dedução da “CONTRIBUIÇÃO OBRIGATÓRIA”. Qualquer indenização patrimonial  somente será paga, mediante apresentação dos documentos requeridos pela Associação São Paulo de Caminhoneiros e observadas todas as condições previstas nesse Regulamento. Parágrafo Segundo. Caberá a Diretoria Executiva a escolha de indenizar integralmente o valor do caminhão, semi-reboque ou equipamento ou mesmo promover o conserto em caso de danos parciais em suas oficinas credenciadas, atendendo e respeitando os seus valores. Parágrafo Terceiro. Associação São Paulo de Caminhoneiros NÃO INDENIZARÁ QUALQUER VALOR REFERENTE AO SERVIÇO DE GUINCHO nos casos de quebra de qualquer espécie, pane elétrica, pane seca, etc. O serviço de guincho somente será atendido pela Associação em caso de acidentes, quando o veículo não reunir condições de tráfego. Nas áreas atendidas conforme o item XI parágrafo segundo.</p>
<p><br />
  XIV. 1 – INDENIZAÇÃO INTEGRAL DO PATRIMÔNIO: Parágrafo Primeiro.  Em caso de indenização integral do(s) veículo(s) ou implemento(s) cadastrado(s). A Associação São Paulo de Caminhoneiros terá um prazo para opagamento de até 60 (sessenta) dias, da entrega de toda documentação exigida e que tenha decorrido nesse período no mínimo duas reuniões  mensais da diretorias da Associação São Paulo de Caminhoneiros. Este pagamento somente será efetuado mediante apresentação de responsabilidade do associado do boletim de ocorrência ou queixa de roubo , da certidão de não localização do(s) veículo(s) e por ventura se for necessário demais documentos, sem prejuízo do relatório da empresa de rastreador. Parágrafo Segundo. Será suspensa a contagem do prazo a indenização, a partir do momento em que for solicitada documentação complementar no caso de dúvida fundada e justificável, sendo reiniciada a contagem do prazo remanescente a partir do dia útil  posterior àquele em que forem apresentados os respectivos documentos. Parágrafo Terceiro. No caso de roubo  a <br />
  Associação São Paulo de Caminhoneiros poderá indenizar o associado com a compra de um veículo semi-reboque ou implemento de mesmo ano, modelo e marca. Desde que, obedeçam ao valor estabelecidos de teto máximo de indenização da tabela FIPE ou teto máximo da indenização do ITEM XIII do presente regulamento, mas se a Associação São Paulo de Caminhoneiros não optar pela compra do veículo semireboque ou implemento a indenização será no valor ajustado nos termos do presente regulamento, via TED (Transferência Eletrônica Disponível) ou documento similar, que disponibilize o valor diretamente na conta corrente ou conta poupança  de titularidade do beneficiário legal do patrimônio protegido, ou seja, SEM RESERVA. <br />
  Parágrafo Quarto. Qualquer indenização integral somente será efetivada mediante a apresentação do documentos que comprovem os direitos de propriedade, livre e desembaraçada de qualquer ônus sobre o patrimônio protegido.</p>
<p> <br />
  XIV.1 “A” PERDA INTEGRAL EM DECORRENCIA DE ACIDENTE (COLISÃO E COLISÃO, INCÊNDIO (meditante acidente)): Parágrafo Primeiro. Haverá indenização integral quando o valor para reparação do bem, apurado pela Associação São Paulo de Caminhoneiros que atingir ou ultrapassar 75% (setenta e cinco por cento) do valor integral previsto na Tabela FIPE,  na data do acidente, desde que o valor do veículo esteja abaixo do teto máximo de indenização patrimonial do presente regulamento, neste caso poderá a Associação São Paulo de Caminhoneiros optar pela compra do referido caminhão, semi-reboque ou implemento, cabendo  o associado o direito de escolha (mesmo ano, marca e modelo). Parágrafo Segundo. O valor a ser indenizado deverá ser realizado de acordo com os valores praticados no mercado de caminhões, semi-reboques ou implementos, obedecendo ao seguinte critério: pagamento mínimo de 70% (setenta por cento) do valor ajustado na tabela FIPE e pagamento  máximo de 100% (cem por cento) do valor ajustado na tabela FIPE devendo sempre ser respeitado o valor máximo estipulado no ITEM XIII. Parágrafo Terceiro. Depois de consumado o fato, a Associação São Paulo de Caminhoneiros criará uma comissão de apuração do valor em reunião especifica, exclusivamente pela diretoria da Associação São Paulo de Caminhoneiros, de forma imparcial visando aproximar a indenização devida ao máximo do valor real praticado no mercado. Parágrafo Quarto. Poderá a Associação São Paulo de Caminhoneiros optar pela compra do caminhão com as mesmas características (marca, modelo e ano) do veículo acidentado, caso em que não será destinada ao associado nenhuma indenização em moeda corrente. <br />
  Parágrafo Quinto. Para os veículos superior ao teto máximo R$ 350.000,00 (trezentos e cinquenta mil reais) haverá indenização deste valor quando o valor  do orçamento  para reparação do bem atingir ou ultrapassar 75% (setenta e cinco por cento) do valor  desse teto na data do acidente. <br />
  Parágrafo Sexto. Nos casos de o caminhão, semi-reboque, ou implemento for alienado fiduciariamente, através de ARRENDAMENTO MERCANTIL, FINAME, FAT ou outra modalidade de financiamento, o associado tem toda a responsabilidade sobre a extinção do seu  contrato de financiamento e liberação imediata do veículo para a Associação São Paulo de Caminhoneiros, que providenciará  a venda das sobras do caminhão, <br />
  semi-reboque ou implemento. A indenização  será feita ao beneficiário, desde que o contrato de financiamento esteja extinto e o veículo liberado. <br />
  Parágrafo Sétimo. Em caso de destruição total do patrimônio protegido em decorrência de colisão o associado em comum acordo poderá optar pelo recebimento dos 75% (setenta e cinco por cento) quitado. Ficando responsável pela recuperação ou destino das sobras do patrimônio protegido. <br />
  Parágrafo Oitavo. Poderá a diretoria da Associação São Paulo de Caminhoneiros em comum acordo com o associado negociar a sobra do patrimônio  protegido, ficando a negociação limitada ao valor integral do bem protegido conforme descrito neste regulamento. <br />
  Parágrafo Nono. Se o veículo for cadastrado nesta modalidade de proteção de acidente, nos termos do presente regulamento, e um terceiro for  o causador do acidente e não possuir qualquer tipo de seguro ou se  recusar  por qualquer motivo, pagar, fica ressalvado que o associado terá de esgotar todas as possibilidades de recebimento do terceiro, o que deverá ser devidamente comprovado, sendo  que a Associação São Paulo de Caminhoneirossomente intervirá neste caso depois de constatado por ela esta recusa, e decorrido no mínimo 5 (cinco) dias úteis do acontecimento. Neste caso, o Associado assumirá o valor da “Contribuição Obrigatória”. Parágrafo Décimo. Caso a Associação São Paulo de Caminhoneiros receba posteriormente do terceiro causador  do  acidente,  o  associado será ressarcido do valor pago referente à “Contribuição Obrigatória”. O restante recebido, depois de abatido as despesas e custas judiciais, se existente, será integrado ao caixa da - Associação São Paulo de Caminhoneiros.</p>
<p><br />
  XIV.1 – “B”- PERDA INTEGRAL EM DECORRÊNCIA DE  ROUBO. Parágrafo Primeiro. Todo veículo para ser indenizado em decorrência de roubo deverá obrigatoriamente possuir um dispositivo de segurança, rastreador e/ou localizador, devidamente homologado pela Associação São Paulo de Caminhoneiros. OBS. Para o patrimônio de até R$ 50.000,00 será suficiente um único rastreador. Para o patrimônio acima de R$ 50.000,01, serão necessários dois rastreadores. Na hipótese da falta do dispositivo de segurança, rastreador e/ou localizador, devidamente homologado pela Associação São Paulo de Caminhoneiros, o ASSOCIADO não  terá direito a ressarcimento.     Parágrafo Segundo. No caso de roubo de um caminhãocadastrado nesta modalidade e se o semi-reboque estiver devidamente cadastrado e acoplado ao mesmo com o implemento devidamente instalado no caminhão através de fotos junto ao laudo de verificação a Associação São Paulo de Caminhoneiros somente pagará o valor do(s) veículo(s) ou implemento se o caminhão cadastrado possuir um sistema instalado de rastreamento ou localização de veículos. Quanto ao sistema de localização poderá ser específico a localizar somente na eventualidade de roubo  do veículo, no caso deste sistema o processo de localização  poderá usar o sistema  de rádio frequência. Fica também  determinado que na eventualidade  de avaria  total  ou parcial de  Roubo. O associado será o responsável pelas manutenções periódicas necessárias e manter as obrigações financeiras determinadas para cada sistema em dia, fica o associado ciente que a Associação São Paulo de Caminhoneiros poderá, segundo sua conveniência, requerer  tal comprovação  ficando o associado responsável pela comprovação dos fatos de documentos específicos. Para  o  pagamento  da indenização ou reposição do patrimônio, é obrigatório um teste mensal no serviço de rastreador(es). <br />
  Caso o sistema não se enquadre no exigido ou o Associado não comprove através de documentos a regularidade financeira e a manutenção do sistema na data exigida, e até mesmo, a não existência ou comprovação de sistema instalado no caminhão, o Associado não terá direito de indenização no caso de roubo . Para o(s) caso(s) de roubo de caminhão(ões) que acompanharem implementos(s) ou semi(s) reboque(s) a apuração do(s) valor(es) deste(s) seguirá os mesmos critérios do item </p>
<p>XIV.3 deste regulamento. <br />
  XIV.2 – CÁLCULO DO VALOR INTEGRAL – CAMINHÃO,  – ROUBO: Parágrafo Primeiro. Em decorrência de roubo de veículo(s) apto(s) e incluso(s) nesta modalidade e que possuam um dispositivo de segurança instalado, devidamente com as manutenções e regularidades financeiras específicas a cada sistema em dia, e após a comprovação de fatos através de documentos, nesta condição será indenizado pelo valor integral do(s) patrimônio(s) protegido(s). Parágrafo Segundo. O valor a ser indenizado deverá ser realizado de acordo com os valores praticados no mercado de caminhões,obedecendo ao seguinte critério: pagamento mínimo de 80% (oitenta por cento) do valor ajustado na tabela FIPE e pagamento máximo de 100% (cento por cento) do valor ajustado na tabela FIPE devendo sempre ser respeitado o valor máximo estipulado no item “ITEM XIII”. Parágrafo Terceiro. Depois de consumado o fato, a Associação São Paulo de Caminhoneiros criará uma comissão de apuração, para tal valor ser definido em reunião específica exclusivamente pela diretoria da Associação São Paulo de Caminhoneiros, de forma imparcial visando aproximar a indenização indevida ao máximo do valor real de mercado de caminhões seminovos e novos, na ocasião do roubo. Parágrafo Quarto. Poderá a AAssociação São Paulo de Caminhoneiros optar pela compra de caminhão, semireboque ou implemento com as mesmas características (marca, modelo e ano) do caminhão roubado  , caso em que não será destinado ao associado nenhuma indenização em moeda corrente. <br />
  Parágrafo Quinto. Se em qualquer época o veículo roubado ou vier a ser recuperado a Associação São Paulo de Caminhoneiros deverá providenciar a venda do bem protegido levando em consideração o estado de conservação que ele se encontra caso em que o valor apurado deverá ser integrado ao caixa da Associação São Paulo de Caminhoneiros.</p>
<p><br />
  XIV.3 – CÁLCULO DO VALOR INTEGRAL – IMPLEMENTO/SEMI-REBOQUE Parágrafo Primeiro. Em decorrência de roubo de caminhão(es), semi(s)-reboque(s) ou implemento(s) apto(s) e incluso(s) nesta modalidade e que possuam dispositivo de segurança instalado, devidamente com as manutenções e regularidades financeiras específicas a cada sistema em dia e após comprovação dos fatos através de  documentos,  e  que  no ato do roubo  acompanharem implemento ou semi-reboque(s) mediante as condições previstas neste regulamento, nesta condição este(s) será(ao) indenizado(s) pelo valor integral do(s) implemento(s) ou semi-reboque(s), de acordo com a  decisão  com  a  comissão  da  Associação São Paulo de Caminhoneiros. Parágrafo Segundo. Para se chegar ao valor da indenização devida do implemento ou semi(s)-reboque(s), neste caso, pelo fato de não existir tabela específica apurada para os tais, a diretoria da Associação São Paulo de Caminhoneiros depois de consumado o fato, criará uma comissão para apuração dos valores do(s) implemento(s) ou semi(s)-reboque(s) baseado no laudo de verificação do(s) mesmo(s). Este valor será definido em reunião específica da diretoria Associação São Paulo de Caminhoneiros de forma imparcial, visando aproximar ao máximo o valor real de mercado do implemento ou semi-reboque(s) na ocasião do  roubo sempre respeitando o teto máximo de indenização do presente regulamento. Parágrafo Terceiro. Se em época o semi-reboque/implemento roubado vir a ser recuperado, a Associação São Paulo de Caminhoneiros deverá providenciar a venda recuperado levando em consideração o estado de conservação que ele se encontra, caso em que o valor apurado deverá ser integrado ao caixa da Associação São Paulo de Caminhoneiros.</p>
<p> <br />
  XIV.4 – INDENIZAÇÃO DANOS MATERIAIS PARCIAIS: Parágrafo Primeiro. A indenização será sempre com base nos custos das partes, peças e materiais a substituir (danificados no acidente de maneira que comprometa o funcionamento do(a) mesmo(a), bem como da mão-de-obra necessária para reparação ou substituição. A Associação São Paulo de Caminhoneiros providenciará o conserto do patrimônio acidentado e o pagamento do valor correspondente, será abatido o valor da “Contribuição Obrigatória”, ficando o associado responsável pelo acerto deste valor junto à Associação São Paulo de Caminhoneiros ou na oficina onde está sendo feito o reparo do patrimônio acidentado. Parágrafo Segundo. Para a comodidade dos associados na eventualidade de um acidente, a Associação São Paulo de Caminhoneiros sugere uma rede de oficinas credenciadas para a reparação dos danos materiais ocorridos no caminhão, semi-reboque e implementos cadastrados. Nesta reparação poderão  ser  utilizadas  peças  em  ótimo  estado de conservação, podendo estas ser novas ou usadas, desde que tenham garantia de procedência e qualidade. Os critérios utilizados para credenciamento destas oficinas serão: qualidade de serviços prestados, os recursos tecnológicos e os equipamentos que esta dispõe. Parágrafo Terceiro. No caso de acidente com danos materiais parciais no bem protegido a recuperação será efetuada o mais breve possível, após a entrega de toda documentação que for requisitada ao associado, na sede da Associação São Paulo de Caminhoneiros, efetuados os devidos orçamentos. Autorizada a execução dos serviços e fornecimento de peças pela diretoria da Associação São Paulo de Caminhoneiros,  que acompanhará todo o processo de recuperação, o associado não terá qualquer direito a ressarcimento de valores gastos em reparos efetuados fora destas condições, em qualquer hipótese. <br />
  Parágrafo Quarto. A recuperação será feita com a reposição de peças originais em concessionárias, somente quando o equipamento estiver com garantia total do fabricante, e a não reposição de peças originais em concessionária ocasionarem na perca da garantia. Parágrafo Quinto. A recuperação será feita pela substituição das peças danificadas pelas similares produzidas no mercado paralelo, desde que não comprometam a segurança e a utilização do equipamento. Parágrafo Sexto. Se o veículo for cadastrado nesta modalidade de proteção de acidentes, nos termos do presente regulamento, em terceiro for o causador do acidente e não possuir qualquer tipo de seguro ou se recusar, por qualquer motivo, a pagar, fica ressalvado que o associado sempre terá de esgotar todas as possibilidades de recebimento do terceiro, o que deverá ser devidamente comprovado, sendo que a Associação São Paulo de Caminhoneiros somente intervirá neste caso depois de constatado por esta recusa, e decorrido no mínimo 05 (cinco) dias úteis do acontecimento. Neste caso, o associado assumirá o valor de “Contribuição Obrigatória”. Caso a Associação São Paulo de Caminhoneiros receba posteriormente do terceiro causador do acidente, o associado será ressarcido do valor pago referente à “Contribuição Obrigatória” e, consequentemente, o restante recebido, depois  de  abatido  despesas e custas judiciais, se existentes, será integrado ao caixa da Associação de Fundo e Auxílio ao Motorista Autônomo - Associação São Paulo de Caminhoneiros. Parágrafo Sétimo. Caso o associado se envolva em um acidente e seja o beneficiário de seguro de danos materiais e corporais a terceiros e o valor recebido não for suficiente para cobrir todos os custos do acidente, a Associação poderá analisar o caso e aprovação pela diretoria da Associação São Paulo de Caminhoneiros.</p>
<p><br />
  XV – PARTICIPAÇÃO OBRIGATÓRIA DO ASSOCIADO EM ACIDENTES “CONTRIBUIÇÃO OBRIGATÓRIA”: Parágrafo Primeiro. Valor definido neste regulamento com o qual o associado participará, obrigatoriamente, em cada acidente que envolva danos parciais ao veículo incluso nesta modalidade. <br />
  Parágrafo Segundo. A PARTICIPAÇÃO DO ASSOCIADO EM ACIDENTES “CONTRIBUIÇÃO OBRIGATÓRIA” deverá ser sempre subtraída do valor do orçamento aprovado a ser pago pela Associação São Paulo de Caminhoneiros, sendo este sempre superior ao valor de “CONTRIBUIÇÃO OBRIGATÓRIA”. Na eventualidade de roubo, perda integral do veículo não se cobra o valor de “CONTRIBUIÇÃO OBRIGATÓRIA” do associado. Parágrafo Terceiro. Somente na eventualidade de roubo dos veículos, implementos e semi-reboques ou perda integral em decorrência de colisão do caminhão, não se cobra o valor de “CONTRIBUIÇÃO OBRIGATÓRIA” do associado.</p>
<p> <br />
  XV.1 – VALOR: Parágrafo Único.  O valor estipulado da “CONTRIBUIÇÃO OBRIGATÓRIA”, no caso de avarias no caminhão cadastrado fica determinado em 3% (três por cento) do valor integral da tabela FIPE do respectivo caminhão acidentado, (respeitando o limite do teto máximo de indenização patrimonial) na data do ocorrido acidente. A tabela substituída (segunda tabela de referência será divulgada pela revista MOLICAR e será  utilizada  em  caso de extinção ou interrupção da tabela de referência adotada originalmente).</p>
<p> <br />
  XV.2 – CONDIÇÃO DO PAGAMENTO: Parágrafo Único. Fica determinado que a forma do pagamento da “CONTRIBUIÇÃO OBRIGATÓRIA”, será à vista, podendo ser dividido durante o reparo do caminhão, o reparo será imediatamente paralisado pelo descumprimento desta obrigação por parte do associado. O pagamento da “CONTRIBUIÇÃO OBRIGATÓRIA” poderá também ser negociado pelo associado diretamente com a oficina credenciada que esteja efetuando o reparo desde que autorizado pela diretoria da Associação São Paulo de Caminhoneiros. </p>
<p>XVI – OBRIGAÇÕES DO ASSOCIADO: <br />
  a) cumprir com as determinações financeiras descritas nos “itens X e IX do presente regulamento. <br />
  b) manter o veículo em bom estado de conservação e funcionamento. <br />
  c) dar imediato <br />
  conhecimento à Associação São Paulo de Caminhoneiros caso haja: 1. mudança de endereço para correspondência; 2. alteração na forma de utilização do veículo; 3. transferência de propriedade; 4. alteração das características do veículo.<br />
  <br />
XVI.1 – EM CASO DE ACIDENTE PROTEGIDO NESTE REGULAMENTO: a) o associado deve tomar, o mais depressa possível, todas as providências ao seu alcance para proteger o veículo acidentado para evitar aumento de prejuízos; b) o associado deverá comunicar imediatamente à Associação São Paulo de Caminhoneiros por telefone em caso de acidentes, roubo  do(s) veículo(s) cadastrado(s); c) não fazer reparos sem prévia autorização da Associação São Paulo de Caminhoneiros. Deverá aguardar autorização da  .  Associação dos Caminhoneiros  do Estado de São Paulo para iniciar a reparação de quaisquer danos; d) em caso de acidente, roubo,  o associado deverá providenciar Boletim de Ocorrência junto ao órgão competente; e) em acidente com envolvimento de terceiros, identifica-los, quando possível, no Registro Policial da Ocorrência. Neste documento deve constar: 1. Nome completo, RG, CPF, endereço e telefone do terceiro; 2. Nome completo, RG, CPF, endereço e telefone de duas testemunhas do acidente, se houver. f) informar às autoridades policiais em caso de desaparecimento, roubo do veículo cadastrado. Caso o mesmo possua dispositivo de segurança considerado pela Associação São Paulo de Caminhoneiros ou não, acionar, tão logo seja possível, a empresa prestadora de serviço para as devidas providências com relação ao bloqueio, rastreamento ou localização do veículo. g) dar imediato aviso quando solicitado pela Associação São Paulo de Caminhoneiros a respeito do ocorrido, relatando completamente e minuciosamente o fato, mencionando dia, hora, local, circunstância do acidente, nome, endereço e carteira de habilitação de quem dirigia o veículo, nome e endereço de testemunhas e providências de ordem policial tomadas. Tudo mais que possa contribuir para esclarecimento da ocorrência deve ser comunicado à Associação São Paulo de Caminhoneiros, bem como a identificação do causador do acidente e dos terceiros envolvidos.</p>
<p><br />
  XVII – VERIFICAÇÃO: Parágrafo Primeiro. A verificação deverá ser feita por um funcionário apto da Associação São Paulo de Caminhoneiros ou uma pessoa apta a tal função mediante autorização específica. Esta deverá constar através de um laudo de verificação com fotos digitais, decalques e outros dados que identifique o veículo. <br />
  Parágrafo Segundo. Será necessária verificação prévia nas seguintes situações (para que se faça valer este regulamento): <br />
  a. Antes da inclusão do(s) veículo(s) nesta modalidade; b. Exclusão de avarias; c. Substituição de veículo; d. Inclusão   e   substituição   de   semi(s)-reboque(s)  e implemento(s); e. Alteração significativa no veículo; f. Do veículo acidentado antes dos reparos; g. Do veículo imediatamente após reparado os estragos de um acidente. Parágrafo Terceiro. Ocorrendo acidente protegido nesta modalidade envolvendo partes ou peças que constem no relatório de verificação como avarias (e que não tenham informado tal reparo a Associação São Paulo de Caminhoneiros). O valor de tais avarias será deduzido da indenização a ser paga. <br />
Parágrafo Quarto. Associação São Paulo de Caminhoneiros não faz, na verificação prévia nenhuma avaliação do valor de mercado do veículo, nem da legalidade de sua procedência.</p>
<p><br />
  XVIII – OS RISCOS E PREJUÍZOS QUE A PROTEÇÃO DE ACIDENTES EM VEÍCULOS – NÃO INDENIZA:  a) lucros cessantes e danos emergentes direta o indiretamente da paralisação do(s) veículo(s) cadastrado(s), mesmo quando em consequência de risco protegidos pelo presente regulamento;  b) percas ou danos ocorridos quando em trânsito por estradas ou caminhos impedidos, não abertos ao tráfego ou de areias fofas ou movediças, ou ponte de madeira ou balsas flutuantes; c) danos causados à carga transportada;  d) percas ou danos ocorridos durante a participação do veículo em competição,  aposta,  provas  de  velocidade,  inclusive  treinos preparatórios;  e) danos e ou avarias aos acessórios e equipamentos;  f) multas e fianças impostas ao associado e despesas de qualquer natureza relativas à ações e processos criminais;  g) as avarias que forem previamente constatadas e relacionadas na Verificação Prévia do veículo associado nos acidentes com danos materiais parciais;  h) as avarias não relacionadas com o acidente protegido;  i) danos decorrentes de atos ilícitos cometidos pelo associado, seus dependentes, representantes ou prepostos;  j) reparos dos veículos à revelia e sem a autorização da Associação São Paulo de Caminhoneiros;  k) àqueles que não se encontrarem no conceito de proteção da do(s) veículo(s) e os riscos decorrentes da inobservância das leis em vigor;  l) desgaste natural o pelo uso, deterioração gradativa e vício próprio, defeito  fabricação,  defeitos mecânicos, da instalação elétrica do veículo, vibrações, corrosão, ferrugem, umidade e chuva;  m) quaisquer atos de hostilidade ou guerra, tumultos, passeata, protesto, motins, comoção civil, sabotagem e vandalismo;  n) radiação de qualquer tipo;  o) poluição, contaminação e vazamento;  p) furacões, ciclones, terremotos, erupções vulcânicas e outras convulsões da natureza, inundação e enchente; q) atos de autoridades públicas salvo para evitar propagação de danos protegidos;  r) negligência do associado, arrendatário o cessionário na utilização, bem como, na adoção de todos os meios razoáveis para salva-los e preservá-los durante ou após a ocorrência de qualquer acidente;  s) acidentes ocasionados pela inobservância de disposições legais como dirigir sem possuir carteira de habilitação ou estar com a mesma suspensa e/ou vencida, ou ainda, não ter habilitação adequada conforme a categoria do veículo, utilizar inadequadamente o veículo com relação à lotação de passageiros, peso e acondicionamento de carga transportada;  t) atos praticados em estado de insanidade mental e/ou sob efeito de bebidas alcoólicas e/ou substância tóxica; <br />
  u) danos emergentes;  v) ato reconhecidamente perigoso que não seja motivado por necessidade justificada. <br />
  XIX – RESPONSABILIDADE CIVIL FACULTATIVA DE VEÍCULO: NÃO EXISTE PROTEÇÃO! <br />
  XX – DANOS MATERIAIS A TERCEIROS: NÃO EXISTE PROTEÇÃO! <br />
  XXI – DANOS CORPORAIS A TERCEIROS: NÃO EXISTE PROTEÇÃO! <br />
  XXII – DANOS MORAIS A TERCEIROS: NÃO EXISTE PROTEÇÃO! <br />
  XXIII – PROTEÇÕES ADICIONAIS: NÃO EXISTE PROTEÇÃO! <br />
  XXIV – ACIDENTES PESSOAIS DE PASSAGEIROS: NÃO EXISTE PROTEÇÃO! <br />
  XXV – ASSISTÊNCIA 24 HORAS: NÃO EXISTE PROTEÇÃO! <br />
  XXVI – OCORRÊNCIAS QUE CANCELAM A PROTEÇÃO DE ACIDENTES EM VEÍCULOS: <br />
  a) o não cumprimento de obrigações impostas e aceitas, descritas neste regulamento; b) a proteção do(s) veículo(s) será cancelada automaticamente quando o risco se filiar a atos ilícitos do associado, do beneficiário da proteção do(s) veículo(s), ou dos representante e prepostos, quer de um, quer de outro; c) caso o associado faça a opção de CONTRATAÇÃO DA PROTEÇÃO DE ACIDENTES EM VEÍCULOS, oferecido pela Associação São Paulo de Caminhoneiros, em hipótese alguma, será admitida participação do veículo incluso nesta modalidade, em outra modalidade similar a esta e, inclusive, a participação em seguro particular de casco, sob pena de tornar-se nula a presente proteção. Salvo seguro de danos materiais e corporais a terceiros, tendo em vista que a Associação São Paulo de Caminhoneiros não assume qualquer indenização a terceiros; d) caso um veículo cadastrado nesta modalidade se envolva em dois acidentes com um mesmo motorista, num período de 01 (um) ano e fique constado nestes dois acidentes, pela Associação São Paulo de Caminhoneiros, imprudência, negligência ou imperícia desde motorista ao dirigir, ficará o caminhão cadastrado sem proteção nesta modalidade quando se envolver em um terceiro acidente com este mesmo motorista antes de se passar 01 (um) ano do segundo acidente; <br />
  e) o não cumprimento de obrigações estabelecidas e impostas em edições ou versões atualizadas e alterações parciais, previamente informadas deste regulamento; f) quaisquer alterações referentes ao veículo cadastrado, incluindo sua forma de utilização e transferência de propriedade, sem a devida comunicação à  .  Associação  dos  Caminhoneiros do Estado de São Paulo. Importante: os direitos e obrigações deste regulamento não se transferem automaticamente com a venda do(s) veículo(s) cadastrado(s). <br />
</p>
<p>XXVII – OCORRÊNCIAS QUE TORNAM A PROTEÇÃO DE ACIDENTES EM VEÍCULOS SEM EFEITO: Além dos acidentes diretamente ocasionados pela inobservância às disposições legais, a A. Associação dos Caminhoneiros do  Estado  de  São Paulo  ficará  isenta  de  qualquer obrigação decorrente do contrato de proteção do(s) veículo(s) em caso de: a) omissão ou inexatidão de informações pelo associado, em qualquer época que sejam fundamentais para aceitação da inclusão do(s) veículo(s) associado; Incluí-se na definição <br />
  acima: Quaisquer alterações referentes ao veículo cadastrado, incluindo sua forma de utilização e transferência de propriedade, sem a devida comunicação à Associação São Paulo de Caminhoneiros. b) qualquer informação incorreta ao associado na proposta de proteção do(s) veículo(s); c) omissão ou inveracidade de informações na comunicação de acidente à Associação São Paulo de Caminhoneiros, relativo à: 1. causa; 2. natureza; 3. gravidade; 4. causador do evento, bem como qualquer outro fato ou informações fundamentais para conclusão do processo de acidente. d) fraudes ou atos contrários à lei por parte do associado, beneficiários, representantes ou usuários dos bens cadastrados; <br />
e) submeter o bem cadastrado a riscos desnecessários ou atos imprudentes antes, durante e após um acidente, bem como agravar os danos ou expor-se a situações que comprometam a segurança e a integridade física do(s) mesmo(s); f) nos casos de guerra, motim, revolução e ocorrências semelhantes. Ou seja, acidentes que atinjam de forma maciça a população regional ou nacional. XXVIII – DA SOBRAS DO CAMINHÃO / SEMI-REBOQUE / IMPLEMENTOS: Parágrafo Primeiro. Ocorrido os acidentes, o associado não pode abandonar as sobras e deve tomar as medidas possíveis para sua proteção. Parágrafo Segundo. Indenizado o acidente, todas as sobras passam automaticamente, livres e desembaraçados de quaisquer ônus, à propriedade da Associação São Paulo de Caminhoneiros. Parágrafo Terceiro. A Associação São Paulo de Caminhoneiros não tem qualquer responsabilidade sobre o destino final das sobras. No entanto, cabe à entidade dar preferência de compra à pessoas credenciadas e/ou de credibilidade junto ao mercado de compra de sobras dos caminhões / semi-reboques / implementos para que o destino final destes equipamentos esteja dentro de todos os procedimentos legais.</p>
<p> <br />
XXIX – PROCEDIMENTOS DE DOCUMENTAÇÃO EM CASO DE ACIDENTES PROTEGIDOS PELA – PROTEÇÃO DE ACIDENTES EM VEÍCULOS: </p>
<p><br />
  XXIX.1. DOCUMENTAÇÃO NECESSÁRIA: Parágrafo Único. Todas as documentações solicitadas pela Associação São Paulo de Caminhoneiros para a indenização de um acidente serão de responsabilidade do associado, que deverá providenciar sua entrega na sede da Associação, sob pena de não receber o valor da indenização. Se caso fizer necessário, deverá fornecer uma procuração, dando plenos poderes e direitos a um advogado nomeado pela Associação São Paulo de Caminhoneiros, para questões perante terceiros envolvidos em acidente que seja de interesse da Associação São Paulo de Caminhoneiros.  A) EM CASO DE DANOS PARCIAIS (ACIDENTES) NO VEÍCULO, PESSOA FÍSICA OU JURÍDICA: 1. Cópia da CNH do condutor no ato do acidente; 2. Cópia do comprovante de residência do condutor no ato do acidente; 3. Cópia do Boletim de Ocorrência Policial; 4. Xerox do CRLV – Certificado de Registro e Licenciamento do Veículo do ano em vigor; 5. quando o associado não for culpado pelo acidente, e for constatada a recusa do terceiro em pagar, apresentar documentação específica solicitada à parte.  B) EM CASO DE INDENIZAÇÃO INTEGRAL DECORRENTE DE ACIDENTE DE VEÍCULO CADASTRADO: B.1. – PESSOA FÍSICA: 1. Cópia do CPF e RG do proprietário do(s) veículo(s); 2. Comprovante de residência do proprietário do veículo; 3. CRV – Certificado de Registro de <br />
  Veículo original (Recibo de Transferência), preenchido em favor da Associação São Paulo de Caminhoneiros ou de quem ela indicar, assinado com firma reconhecida por autenticidade; 4. Cópia da CNH do condutor no ato do acidente; 5. Cópia do comprovante de residência do condutor no ato do acidente; 6. Boletim de Ocorrência original e autenticado por órgão competente; 7. Xerox do CRLV – Certificado de Registro e Licenciamento do veículo do ano em vigor; 8. Quando o associado não for culpado pelo acidente, e for constatada a recusa do terceiro em pagar, apresentar documentação específica solicitada pela Associação São Paulo de Caminhoneiros à parte; <br />
  9. CRLV Certificado de Registro e Licenciamento do veículo original com o Seguro Obrigatório – DPVAT quitado (último exercício); 10. IPVA’s originais quitados (exercício atual e anterior), ou comprovação quando for o caso, da isenção do pagamento do IPVA’s, expedida pela Secretaria da Fazenda Estadual; 11. Extrato do DETRAN, onde deve a situação do veículo (proprietário, débitos e demais restrições se houver). Caso haja alguma restrição, devem ser regularizadas, e após, providenciada nova consulta ao DETRAN original. Caso o DETRAN ou CIRETRAN regional não forneçam  a  simples  consulta,  anexar  o  extrato  com negativa de multas expedidas pelo DETRAN; 12. Chaves do veículo, quando houver; 13. Manual do proprietário, quando houver; 14. Termo de Responsabilidade, contendo os dados do veículo, eventuais multas e débitos existentes até a data do acidente com firma reconhecida por autenticidade do proprietário do veículo; 15. Recibo específico assinado, com autenticidade reconhecida em cartório, fornecido pela Associação São Paulo de Caminhoneiros. Caso o veículo seja financiado, arrendado, alienado ou algo similar, deve ainda ser providenciada:     Liberação do(s) mesmo(s) junto à financeira ou Termo de Liberação do Bem (originais), com firma reconhecida por autenticidade das assinaturas, quando se trata, respectivamente, de veículo financiado ou arrendado. <br />
  B.2 – PESSOA JURÍDICA <br />
1. Cópia do Cartão do CNPJ;  2. Cópia do Contrato Social – primeira a última alteração social;  3. CRV – Certificado de Registro do Veículo – original (documento de transferência), preenchido e assinado com firma reconhecida por autenticidade e carimbo da empresa, sendo que as assinaturas devem ser dos sócios que possuem poderes para vender bens da empresa. Caso esses não constem no Contrato Social, anexar cópia da procuração de quem assino o CRV de transferência ou documento similar; 4. Carta com declaração assinada, com firma reconhecida das assinaturas pelo contador da empresa informando baixa do(s) veículo(s) a ser(em) indenizado(s). Deverá ainda anexar cópia da identidade profissional .  C – EM CASO DE INDENIZAÇÃO INTEGRAL DECORRENTE DE ROUBO OU  TANTO CAMINHÃO QUANTO DO SEMI-REBOQUE: Utilizar a relação de documentos exigidos na alínea B.1 ou B.2, além de:  1. Extrato do DETRAN (débitos e restrições) constando queixa de roubo   2. Certidão de não localização do(s) veículo(s);  3. Em caso de veículo equipado com dispositivo de segurança tipo localizador ou rastreador, a documentação já especificada no presente regulamento “item.</p>
<p><br />
XIV. I-B”. FICA RESSALVADO O DIREITO DA Associação São Paulo de Caminhoneiros DE SOLICITAR, ALÉM DOS DOCUMENTOS MENCIONADOS, QUAISQUER OUTROS DOCUMENTOS QUE JULGAR NECESSÁRIO. XXX – ALIENAÇÃO OU RESERVA DE DOMÍNIO: Parágrafo Único: Fica entendido e concordado que todo e qualquer pagamento de indenização patrimonial integral, somente será pago com a prévia e expressa anuência do(s) detentor(es) este(s), expressamente especificado no certificado de propriedade do veículo.</p>
<p> <br />
XXXI – SUB-ROGAÇÃO DE DIREITOS: Parágrafo Único. Com o pagamento das indenizações relativas ao item XIV a Associação São Paulo de Caminhoneiros ficará sub-rogada, até o limite pago, acrescido de custas judiciais e honorários advocatícios, em todos os direitos e ações do associado contra aquele que por ato, fato ou omissão tenham causado os prejuízos o para eles contribuído A SUB-ROGAÇÃO OPERARÁ CONSOANTE DISPÕE O LIVRO I, TÍTULO III, CAPÍTULO III DA PARTE ESPECIAL DO CÓDIGO CIVIL.</p>
<p> <br />
XXXII – FORO: Parágrafo Único. Para ações fundadas em direitos ou obrigações decorrentes deste contrato, prevalecerá o foro da sede da Associação São Paulo de Caminhoneiros.</p>
<p> <br />
  XXXIII – GLOSSÁRIO: Parágrafo Único. A seguir, as definições dos termos apresentados no presente regulamento: Acessório: Entende-se como acessório rádio, rádio PX, toca-fitas, CD players, televisões, climatizadores de ar, rodo ar, comando hidráulico, motores de câmaras frias, ferramentas, amplificadores, alto-falantes, rodas de alumínio, sistema de localização e rastreamento originais ou não de fábrica, desde que fixados de forma permanente no veículo. Todos os itens designados como acessórios, especificados aqui ou não, não serão protegidos nesta modalidade. Associado: Pessoa física ou jurídica que contrata a PROTEÇÃO DE ACIDENTES EM VEÍCULOS, modalidade oferecida pela Associação São Paulo de Caminhoneiros ao seu associado, em seu benefício próprio, em relação a qual a Associação São Paulo de Caminhoneiros e o associado assumem a responsabilidade dos riscos previstos neste regulamento, desta modalidade. Avarias Prévias: Danos existentes no veículo antes da inclusão do mesmo nesta modalidade, ou antes de um acidente tais como ferrugem, amassamento e riscos. Aviso de Acidente: É a comunicação feita pelo associado ou terceiro, com a finalidade de dar conhecimento imediato à Associação São Paulo de Caminhoneiros da ocorrência de um acidente visando evitar ou minimizar a extensão dos prejuízos. Esta comunicação deve ser feita o mais rápido possível. Beneficiário: O associado da Associação São Paulo de Caminhoneiros, proprietário legal do(s) veículo(s) incluso(s)  e  apto(s)  previamente  indicar  o(s)  beneficiário(s) que receberá na proporção de 50% (cinquenta por cento) do valor total da indenização, caso não seja feita esta indicação passará na mesma proporção aos herdeiros subsequentes legais. <br />
  Contribuição Obrigatória: Valor do percentual definido neste regulamento com o qual o associado participará, obrigatoriamente, em cada acidente que envolva danos parciais ao caminhão incluso nesta modalidade. Diretoria da Associação São Paulo de Caminhoneiros: Conselho administrador desta entidade, no seu mandato legal. Furto: É a subtração de coisa alheia móvel e é caracterizado quando o crime é cometido. O roubo é <br />
  considerado pela Associação São Paulo de Caminhoneiros quando registrado em boletim de ocorrência e instaurado inquérito policial. <br />
  Implemento: Equipamento instalado de forma permanente no caminhão necessário para o exercício das atividades relativas a transportes e movimentação, na grande maioria dos casos determinados como carrocerias, baús e etc. <br />
  Oficina credenciada: Na eventualidade de um acidente, a Associação São Paulo de Caminhoneiros indicará uma oficina credenciada para a reparação dos danos materiais ocorridos aos veículos cadastrados. Os critérios utilizados para credenciamento destas oficinas foram à qualidade dos   serviços   apresentados,   os   recursos   tecnológicos  e equipamentos de que dispõe. <br />
  Regulamentação de Acidente: É a análise interna do acidente avisado à Associação São Paulo de Caminhoneiros, trata-se do processo de avaliação das causas e apuração dos prejuízos devidos ao associado e do direito deste a indenização. <br />
  Responsabilidade Civil: Esta modalidade da Associação São Paulo de Caminhoneiros não assume em hipótese alguma qualquer responsabilidade civil seja qual for o acontecimento. <br />
  Risco: Possibilidade de um acontecimento inesperado e externo, causador de danos materiais ou corporais. As características que definem o risco são: incerto e aleatório, possível, concreto, lícito, fortuito e quantificável. Roubo: É a subtração do bem do associado mediante grave ameaça ou violência à pessoa, ou ainda, a eliminação de resistência da mesma por qualquer meio. O roubo é considerado pela Associação São Paulo de Caminhoneiros quando registrado em boletim de ocorrência e instaurado inquérito policial. Sobras dos caminhões / semi-reboques / implementos: São os objetos que consegue resgatar de um acidente e que ainda possui valor econômico. Assim são considerados tanto os bens que tenham ficado em perfeito estado como os que estejam parcialmente danificadas pelos efeitos do acidente. <br />
  Sede  Administrativa  da  .  Associação  dos Caminhoneiros do Estado de São Paulo: XXXXXXX. <br />
  Semi-reboque: Entende-se como semi-reboque o veículo que é acoplado a um caminhão que destina exclusivamente ao transporte de carga e que tem proteções patrimoniais específicas e determinadas neste regulamento. <br />
  Acidente: Acontecimento previsto neste regulamento da Associação São Paulo de Caminhoneiros de natureza súbita, involuntária, casual, fortuito, casual ou não, e de que resulta dano, estrago, prejuízo, avaria, perca, ruína, etc, ao associado da  .  Associação São Paulo de Caminhoneiros. <br />
  Tabela FIPE: Tabela de cotação de veículos desenvolvida pela Fundação de Pesquisas Econômicas e que está disponível no site: www.fipe.org.br. <br />
  Terceiro: Pessoa que, envolvida num acidente, não represente nenhuma das partes do contrato de proteção do(s) veículo(s) (associado e Associação). Não se incluem na definição de terceiros os proprietários legais dos veículos cadastrados nesta modalidade, nos termos do presente regulamento. Termo de Adesão à proteção de acidentes de veículos: É o documento através do qual a Associação São Paulo de Caminhoneiros formaliza a aceitação do(s) veículo(s), especificado(s) de responsabilidade do associado nesta modalidade diante das regras descritas neste regulamento. Teto Máximo de Indenização Patrimonial: Valor máximo de indenização estipulado neste regulamento para pagamento. Entretanto, ao prévio reconhecimento de quem num eventual acidente, de valor superior, venha a ser liquidado pelo pagamento integral, o limite máximo referente ao tipo de veículo está expresso neste regulamento. <br />
  Verificação: É a inspeção feita para formalização, constatação do estado físico do veículo, na data da execução da mesma. Nesta inclui-se: laudo, fotos digitais, decalques de números de chassis e demais documentos se necessários que identifique o estado físico do veículo verificado. <br />
  São Paulo/Capital, 02 de março de 2013. <br />
  Esta versão do regulamento foi aprovada, por unanimidade, em reunião da Diretoria da Associação São Paulo de Caminhoneiros realizada em sua sede nesta data. <br />
  O presente regulamento, para produzir seus efeitos jurídicos e legais, está registrado no Cartório de Títulos e Documentos da Comarca.
</p>
    </body>
</html>
