<?php 
session_start();
require('../_app/Config.inc.php');

$id= $_GET['id'];

$ver = new Read();
$ver->ExeRead("prevenda", "WHERE id_venda= :p", "p={$id}");
$ver->getResult();

?>
<DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="windows-1252">
        <title>Contrato Protege</title>
        <?php
require('./estilo.css');
?>
    </head>
    <body>
        
         <header class="cabecalho"> 
            <div class="logoadesao">
                <img src="img/contrato.png" style="width:500; margin: 0 auto;"  />
            </div>
                    <div class="clear"> </div>
            <div class="sessao"> 
                <p> Contrato Nº <?= $ver->getResult()[0]['codigo']; ?>  </p>
                </br>
            </div>
        </header>




CONTRATO DE PRESTAÇÃO DE SERVIÇOS DE EMISSÃO DE SINAIS PARA RASTREAMENTO DE MOTOS, AUTOMOVEIS E OUTROS VEÍCULOS AUTOMOTORES À DISTÂNCIA COM PACTO ADJETO DE PROMESSA DE COMPRA SOBRE EQUIPAMENTO E ASSISTÊNCIA GUINCHO 24 HRS (MARÇO-2012)

1. INTRODUÇÃO E CONCEITOS 1.1 A PROTEGCAR PROTEÇÃO E RECUPERAÇÃO DE VEÍCULOS LTDA, é uma sociedade empresária limitada, inscrita no CNPJ/MF sob nº 05.128.637/0001-81, com sede na Rua Cantagalo, nº 1145, Bairro: Vila Gomes Cardim, CEP: 03319-001, na cidade de São Paulo/SP, que opera serviços de rastreamento e ativação de sistemas de alarmes a distância contra furtos e roubos, bem como recuperação de veículos avariados, doravante denominada “CONTRATADA”. O CONTRATANTE é a pessoa física ou jurídica que contrata os serviços prestados pela CONTRATADA. 
1.2 Este Contrato contém, dentre outras informações, orientações sobre a forma de uso do Sistema, termo de garantia e serviço de assistência técnica autorizada/credenciada dentro e fora do período de garantia do equipamento rastreador. 
1.3 O SISTEMA RASTREADOR é aquele que permite a seu usuário requerer da Central de Operações da CONTRATADA a geração de mapas suficientes para indicar o local no qual o veículo, parado ou em movimento, se encontra. O usuário poderá ainda visualizar por si, diretamente ou, por pessoas autorizadas, o deslocamento do bem em tempo real via internet. 
1.3.1 O Sistema é composto por um Kit que contém: 1 (um) módulo eletrônico; 1(um) conjunto de chicote completo; 1 (uma) antena de GPS e 1(uma) antena de GPRS. Demais periféricos (como sensores e atuadores) utilizados na TELEMETRIA serão adquiridos pelo CONTRATANTE separadamente, mediante pagamento de preço de produto, não se confundindo com o preço pago pela prestação de serviços ou com preço do kit básico de rastreamento. 
1.4 A CONTRATADA mantém por si ou por empresas sub-contratadas, material técnico, humano e infra-estrutura para atender o CONTRATANTE no tocante à prestação de serviços 24 (vinte e quatro) horas por dia, todos os dias do ano, dando, desta forma, regular cumprimento ao Contrato. 
1.5. Para a transmissão dos sinais necessários para a prestação de serviços a CONTRATADA utilizará sistemas de comunicações diversos, individualmente ou de forma combinada, tais como radiofreqüência, telefonia móvel (ERB) e/ou sistema satelital. Vide cláusulas 3.3 e 3.3.1. 
1.6 O Sistema se apóia nos canais de comunicação, no funcionamento eletrônico e no funcionamento da aparelhagem adquirida pelo CONTRATANTE. Desta maneira, deve haver sempre o acompanhamento, por parte do CONTRATANTE do perfeito funcionamento do Sistema e de sua função de rastreamento. Se houver falha na comunicação, o CONTRATANTE deverá imediatamente comunicar-se com a CONTRATADA para que esta possa sanar o problema se o mesmo decorrer de falha do sistema. 
1.7 O SISTEMA DE SEGURANCA PROTEGCAR PROTEÇÃO NÃO É E NÃO EQUIVALE A UM CONTRATO DE SEGURO. A CONTRATADA é uma empresa de PRESTAÇÃO DE SERVIÇOS. NÃO É UMA SEGURADORA E NÃO EXPLORA ATIVIDADE SECURITÁRIA, sendo certo que pela natureza do contrato ora celebrado, suas obrigações são exclusivamente de meio, não havendo qualquer obrigação de resultado, especialmente no tocante à eventual obrigação de recuperação do bem, de suas partes, ou acessórios, ou carga em caso de furto ou roubo total ou parcial. 
1.8 O Sistema pode causar o descarregamento da carga da bateria, podendo, portanto, ser necessária a adaptação deste conforme as especificações de uso do veículo. Não havendo a adequação do Sistema, a CONTRATADA não será responsável pelos danos eventualmente causados em virtude de referido descarregamento da carga. 
2. SERVIÇOS 
2.1 - O objeto básico da prestação de serviços ora avençada é o rastreamento do veículo dentro dos limites do território nacional, respeitados os limites decorrentes das áreas de sombra, conforme cláusulas 3.3 e 3.3.1 deste contrato. 
2.2 O processamento eletrônico, mecânico ou humano das obrigações da CONTRATADA, previstas neste Contrato somente serão realizadas mediante requerimento do CONTRATANTE, ou por pessoa por ele autorizada, mediante uso de senha. 
2.3 O serviço adquirido não é e não engloba qualquer tipo de gerenciamento de risco, não resultando em responsabilidade da CONTRATADA as conseqüências de qualquer natureza (patrimonial ou extrapatrimonial) advindas do seqüestro de pessoas ou do roubo parte ou acessórios do bem, ou ainda, de parte ou totalidade de carga, quando da ocorrência de roubo ou furto do bem. 
3. LIMITAÇÕES DO PRODUTO E DO SERVIÇO 
3.1 Este sistema não é infalível, e não enseja qualquer garantia de resultado, pois a natureza móvel do veículo (igualmente de suas partes, acessórios ou carga) não será modificada pelo seu rastreamento. Tal serviço objetiva acompanhar o bem, desincentivar a conduta criminosa e permitir ao CONTRATANTE um controle sobre a forma de uso do bem, não sendo capaz de impedir ou evitar a consumação de qualquer desiterato criminoso. 
3.2 A contratada garante que acionada por meio de sua Central de Operações, manterá conexão com o sistema rastreador não podendo, porém, garantir que referidos sinais enviados ao equipamento receptor serão recebidos, em razão do serviço estar sujeito à limitações decorrentes de interferências oriundas de topografia, relevo, túneis e condições atmosféricas, os quais poderão ocasionar “áreas de sombra”. 
3.3 Para efeitos deste Contrato, área de sombra é aquela na qual o sinal emitido pela CONTRATADA é afetado pela ausência de elementos capacitadores da disseminação dos sinais enviados ou pela presença de elementos impeditivos da continuidade destes. 
3.3.1 Para efeitos deste contrato de prestação de serviços, entende-se como ACE (ÁREA DE COBERTURA EFETIVA) a área de cobertura oferecida pelas operadoras de telefonia móvel e de radiofreqüência, nos moldes exigidos e regulamentados pela ANATEL, disponíveis no site da referida Agência Reguladora. 
4. SERVIÇOS EXCEDENTES 
4.1 Os seguintes serviços excedentes serão cobrados separadamente: (i) a transferência do Sistema de um veículo para outro (por exemplo, retirada e reinstalação ou somente um destes); (ii) a transferência de titularidade do contrato; (iii) vistoria do veículo no caso de renovação dos serviços; (iv) nova vistoria em decorrência de troca de veículo; (v) nova vistoria para constatação de reparos de avarias constatadas anteriormente; (vi) inadimplência por período superior a 10 (dez) dias, ou, ainda, nos casos de (vii) vistoria após localização e recuperação do veículo nos casos de roubo ou furto. 
4.2 Estes serviços serão cobrados independentemente de promoções relacionadas ao contrato principal. O custo de cada um dos serviços e a forma de pagamento, sempre serão informados pela CONTRATADA ao CONTRATANTE, por meio da Central de Operações, no momento da solicitação da prestação dos serviços, de acordo com o preço constante da tabela vigente à época. 
4.3 O SISTEMA RASTREADOR SÓ PODE SER TRANSFERIDO DE MOTO PARA MOTO, SENDO INVIÁVEL A TRANSFERÊNCIA DO SISTEMA RASTREADOR INSTALADO EM MOTOS PARA AUTOMÓVEIS, UTILITÁRIOS OU CAMINHÕES, BEM COMO O INVERSO. 
5. OBRIGAÇÕES DA CONTRATADA 
5.1 É obrigação da CONTRATADA manter uma Central de Operações específica para atendimento de comunicados de furto ou roubo, disponível 24 horas por dias, todos os dias do ano, com pessoas habilitadas para oferecerem o respectivo atendimento. 
5.2 É obrigação da CONTRATADA manter serviço específico de atendimento ao consumidor, em dias úteis e no horário comercial, para oferecer informações e orientações sobre instalação, assistência técnica de produto dentro e fora da garantia, transferências de titulares ou de veículos, desinstalação, cobranças e outros que decorrerem de relação firmarda. 
5.3. É obrigação da CONTRATADA instalar o Sistema de rastreamento e de proteção no veículo do CONTRATANTE, através de técnico próprio designado para o ato, o qual também fará em momento anterior ao da instalação, uma VISTORIA do veículo. Referida vistoria poderá ensejar a depreciação do bem e continuidade da contratação ficará a critério do CONTRATANTE, que poderá ou não concordar com o laudo de vistoria. 
5.4 Caso o CONTRATANTE concorde com o laudo de vistoria deverá assiná-lo e, em seguida o Técnico procederá a instalação do sistema. Caso o CONTRATANTE não concorde com o laudo de vistoria deverá assinar termo de pedido de rescisão de contrato, com restituição de valores pagos, seguindo-se as regras de rescisão estabelecidas neste contrato. 
5.5 A CONTRATADA poderá atender ao CONTRATANTE em oficinas, postos e lojas credenciadas, por todo o território nacional, observando-se, contudo, a regra expressa nos itens 5.3 e 5.4, no tocante a elaboração de vistoria previa à instalação e expressa concordância do CONTRATANTE. 
5.6 A VISTORIA poderá ser feita por empresas terceirizadas indicadas pela CONTRATADA, e sempre serão cobradas. Assim, será cobrada a vistoria inicial, bem como, as decorrentes de renovação do contrato e, também, aquelas decorrentes de pagamento da prestação de serviços com atraso superior a 10 (dez) dias, ou decorrentes de recuperação do veículo após furto ou roubo, ou ainda, decorrentes de necessidade de reparo do veículo por acidentes, colisões, enchentes ou qualquer outro evento que possa comprometer a integridade do bem. 
5.7 É obrigação da CONTRATADA fazer as adaptações necessárias ao bom funcionamento do Sistema quando os veículos necessitarem de comprovantes diferenciados, como eletroválvula ou relê, devendo o CONTRATANTE arcar com os custos decorrentes da adaptação. 6. OBRIGAÇÕES DO CONTRATANTE 
6.1 O CONTRATANTE deverá, antes da instalação do sistema, submeter o veículo a uma vistoria. Esta vistoria é obrigatória, gratuita no primeiro ano de vigência e cobrada no caso de renovação do contrato, para nova vigência. Deverá ser feita por técnicos da CONTRATADA ou em bases fixas/postos credenciados pela CONTRATADA. A data da instalação do equipamento servirá de termo inicial para a vigência do pacto adjeto de promessa de venda sobre documentos. 
6.2 O pagamento em dia é dever do CONTRATANTE. O atraso de 1 (um) só dia no pagamento é considerado descumprimento contratual e desobriga a CONTRATADA do dever de conversão do contrato de prestação de serviços em contrato de compra e venda com cláusula especial. O descumprimento relativo ao atraso é averiguado mês a mês e não se acumula. O atraso no pagamento de um mês não prejudica a relação contratual se ocorrer o evento furto ou roubo no mês posterior onde o pagamento tenha sido feito em dia. 
6.3 O cadastramento de senha é obrigação do CONTRATANTE, por meio da qual sua identificação será sempre realizada. Caso o cliente não se recorde desta, deverá responder a um questionário que o identificará. O cadastramento da senha permite ao CONTRATANTE o seu login à internet para acompanhamento do rastreamento e das funções de telemetria, assim como, sua identificação do CONTRATANTE será iniciado o processo de atendimento. O retardamento do atendimento do CONTRATANTE em face de o mesmo não se recordar de sua senha não configurará inadimplemento da CONTRATADA, mas sim culpa exclusiva deste. 
6.4 É obrigação do CONTRATANTE a imediata comunicação do furto/roubo à CONTRATADA e às autoridades competentes (Polícia Militar 190 e Polícia Civil 181) e, em caso de recuperação do veículo, efetuar o registro da recuperação perante as autoridades acima mencionadas. 
6.5 É obrigação do CONTRATANTE, após a recuperação do veículo comunicar-se com a CONTRATADA para que esta possa proceder a uma nova vistoria do veículo e também do sistema de proteção veicular para apurar eventual violação do sistema e a necessidade de reparo ou de substituição do mesmo. Estando o sistema violado, o custo para a reposição de peças do kit ou a sua substituição integral deverá ser suportado pelo CONTRATANTE. 
6.6 É obrigação do CONTRATANTE comunicar a CONTRATADA sobre eventuais reparos mecânicos ou elétricos que sujeitar o veículo protegido, decorrentes de desgaste natural, viagens longas, intempéries ou acidentes, pois todas estas circunstâncias podem resultar em vício no funcionamento do Sistema. 
6.7 O teste mensal é obrigatório e faz parte do dever de manutenção do Sistema. A falta de teste no mês da ocorrência do roubo ou furto configura ato culposo do CONTRATANTE e exonera a CONTRATADA do pacto adjeto de compromisso de compra sobre documentos, independentemente do cumprimento das demais obrigações contratuais. 
7. EXCLUSÕES DE RESPONSABILIDADE POR FATORES EXTERNOS 
7.1 Por depender de fatores externos, como por exemplo, a disponibilidade de sinais de comunicação para o perfeito funcionamento do Sistema, a CONTRATADA não será responsável por qualquer falha, interferência ou interrupção dos serviços ora contratados, decorrentes de pane do sistema público de telecomunicações, paralisação de serviços públicos, tempestades, e demais casos fortuitos ou de força maior. (Ex. Maremoto/Terremoto). 
7.2 A CONTRATADA não é responsável por dano, violação, furto ou roubo de cargas, partes ou objetos deixados dentro do veículo, pois o serviço de rastreamento não é e não se confunde com um contrato de seguro, não tem fim investigatório ou ressarcitório, não sendo, portanto, o rastreamento capaz de impedir o furto ou roubo integral ou parcial do próprio bem, de cargas, de objetos móveis ou semoventes deixados dentro do mesmo. 
8. DA INADIMPLÊNCIA 
8.1 A CONTRATADA NÃO PRESTARÁ QUALQUER SERVIÇO PREVISTO OU DECORRENTE DESTE CONTRATO PARA O CONTRATANTE QUE ESTIVER FINANCEIRAMENTE INADIMPLENTE. 
8.2 Será considerado inadimplente o CONTRATANTE para fins deste contrato: (i) o CONTRATANTE que não cumprir com os deveres constantes deste contrato, incluindo, mas não se limitando ao dever de pagamento em dia (PRESTAÇÃO DE SERVIÇOS e KIT); (ii) ao dever de proceder as vistorias do veículo, em face da ocorrência dos eventos que a determinam, de acordo com as disposições deste contrato; (iii) dever de estar devidamente habilitado (habilitação compatível com a categoria do veículo – ex.: categoria A para motos; B para carros de passeio). 
8.3 Na hipótese do CONTRATANTE não efetuar qualquer pagamento à CONTRATADA em razão das obrigações decorrentes deste Contrato, os serviços não serão prestados. A retomada da prestação de serviços está condicionada à comprovação da regularização do pagamento. 
8.4 O PACTO ADJETO DE PROMESSA DE COMPRA SOBRE DOCUMENTOS NÃO SERÁ EFETIVADO SE, NA DATA DO FURTO/ROUBO O CONTRATANTE ESTIVER INADIMPLENTE EM RELACAO: (I) A QUALQUER PAGAMENTO DEVIDO À CONTRATADA; OU (II) AO DEVER DE SOLICITAR O TESTE; OU AINDA, (III) AO DEVER DE SUBMETER O VEICULO A NOVAS VISTORIAS, CONFORME OCORRENCIAS PREVISTAS NESTE CONTRATO; (IV) NÃO SE ENCONTRE DEVIDAMENTE HABILITADO. 
9. COBRANÇAS 
9.1 O não recebimento do boleto referente à cobrança da aquisição do Sistema e/ou prestação de serviço até a data do vencimento não exime o CONTRATANTE da sua obrigação, devendo efetuar o pagamento até a data de vencimento. O pagamento com atraso ensejará a cobrança de juros legais de 1% (um por cento) ao mês e correção monetária pelo INPC – FIPE e, na sua falta, o que vier a substituí-lo, bem como multa de 2% (dois por cento)ao mês. O pagamento dos encargos devidos pela mora não se configuram atenuantes do descumprimento contratual e, no mês que ocorrer o pagamento com atraso o pacto adjeto de promessa de venda sobre documentos no caso de furto ou roubo, NÃO PRODUZIRÁ EFEITOS, em face do inadimplemento contratual do CONTRATANTE. Esta penalidade não é cumulativa e será analisada mês a mês. 9.2 A partir do 30° (trigésimo) dia contado da data da assinatura do Contrato, o CONTRATANTE fica obrigado a pagar a MENSALlDADE referente ao serviço de monitoramento prestado no mês vencido. A prestação de serviços poderá ser contratada com desconto, em razão do pagamento antecipado, na forma de pacotes promocionais. 
9.3 A partir do 5º (quinto) dia de atraso TODOS OS SERVIÇOS ESTARÃO SUSPENSOS e o CONTRATANTE será desabilitado da base da CONTRATADA. O boleto poderá ser pago na rede bancária até 10 (dez) dias corridos de seu vencimento, após este prazo a rede bancária não estará mais autorizada a receber os boletos. O CONTRATANTE permanece obrigado a pagar os valores vencidos e não quitados em virtude deste Contrato. Para fins de realização do pacto adjeto de promessa de venda sobre documentos bastará 1(um) só dia de atraso para configurar o inadimplemento do CONTRATANTE. 9.4 O CONTRATANTE poderá ser reabilitado na base da CONTRATADA mediante cumprimento das obrigações a seguir cumulativamente: (i) pagamento dos valores vencidos e não quitados; (ii) pagamento de uma taxa de reabilitação, cujo valor será informado ao CONTRATANTE por meio da Central de Operações da CONTRATADA e, após regularização dos pagamentos, deverá o CONTRATANTE permitir que um técnico da CONTRATADA proceda a uma nova vistoria no veículo, sem a qual, não se restabelece o pacto. Mesmo que haja o pagamento, devidamente acrescido dos encargos devidos pela mora, se não for feita nova vistoria o CONTRATANTE não poderá exigir o cumprimento do pacto em caso de roubo ou furto do veículo, ainda que o pagamento permaneça em dia. 
9.5 A ocorrência de desabilitação afasta o dever de cumprimento do pacto adjeto de promessa de compra sobre documentos. O pacto somente volta a obrigar a CONTRATADA quando o CONTRATANTE quitar os débitos e proceder a nova vistoria, nos moldes das cláusulas 6.1, e 9.4. 
10. PRAZO DE VIGÊNCIA DO CONTRATO DE PRESTAÇÃO DE SERVIÇOS COM PACTO ADJETO DE PROMESSA DE COMPRA SOBRE DOCUMENTOS 
10.1 O presente Contrato de prestação de serviços vigerá POR 12 (doze) meses a contar da data de sua assinatura. 
10.2 O pacto adjeto de promessa de compra sobre documentos somente se validará com a instalação do sistema, a qual fica condicionada à execução da vistoria prévia do veículo e respectivo aceite do CONTRATANTE, nas hipóteses em que houver FATOR DE DEPRECIAÇÃO, conforme expressa disposição contratual. 
10.3 Para efeito de cobrança da prestação de serviços, a primeira mensalidade vencerá após trinta dias da assinatura do contrato. 
10.4 O presente contrato poderá ser rescindido por qualquer uma das partes mediante aviso, por escrito, com antecedência de 30 (trinta) dias. O CONTRATANTE é obrigado ao pagamento dos serviços relativos ao período mencionado nesta Cláusula, bem como a CONTRATADA deverá manter a prestação destes em iguais condições. A rescisão imotivada deverá respeitar o disposto nas condições gerais deste contrato. 
10.5 O presente Contrato será encerrado após o transcurso do prazo previsto na Clausula 10.1, desde que este não seja expressamente prorrogado mediante assinatura de termo próprio e realização de nova vistoria, com pagamento das respectivas taxas. Não se prorrogando o presente Contrato, e findo 12 (doze) meses de sua vigência, nos termos retro estabelecidos, não surgirá qualquer direito ou obrigação para o CONTRATANTE e para a CONTRATADA relativas a este Contrato. 
11. DO PACTO ADJETO DE PROMESSA DE COMPRA SOBRE DOCUMENTOS E DEMAIS AVENÇAS 
11.1 CLÁUSULA MANDATO - Com a assinatura do presente contrato o CONTRATANTE outorga à CONTRATADA poderes especiais para, em caso de furto ou roubo do veículo monitorado, proceder aos atos necessários junto às autoridades judiciais, policiais e administrativas competentes, bem como promover a contratação de outras empresas especializadas com o fim de tentar recuperar o bem. 
11.2 A cláusula 11.1 não ofende a qualquer princípio legal e, em especial não contraria o artigo 51, inciso VIII do Código de Defesa do Consumidor, uma vez que o presente mandato é instituído para a prática de atos favoráveis aos interesses do CONTRATANTE, pois visa auxiliá-lo no intento de otimizar as possibilidades de recuperação do bem. 
11.3 DA PROMESSA DE COMPRA SOBRE DOCUMENTOS DE VEÍCULO - A CONTRATADA compromete-se a comprar do CONTRATANTE os documentos do veículo monitorado caso o mesmo seja objeto de furto ou roubo total, não se estendendo a qualquer outro tipo de crime (como por exemplo, mas não se limitando a estelionato e apropriação indébita e enchente) e não seja recuperado em até 30 (trinta) dias contados da data do evento. A presente promessa poderá se converter em obrigação de compra somente se respeitados pelo CONTRATANTE os deveres contratuais atinentes ao pagamento, vistorias e habilitação. O descumprimento de qualquer destas obrigações por parte do CONTRATANTE configura sua culpa e exonera a CONTRATADA da promessa de compra. 
Parágrafo Primeiro: Também compromete-se a CONTRATADA a comprar os documentos do veículo monitorado caso o mesmo seja objeto de incêndio ou colisão, desde que seja considerada a perda de 75% (setenta e cinco por cento) do bem ou mais a critério da CONTRATADA. 
Parágrafo Segundo: Caso não se atinja o percentual de 75% (setenta e cinco por cento) do bem, a CONTRATADA está obrigada a recuperar as avarias em oficinas credenciadas por ela e com o pagamento da contribuição obrigatória de 5% (cinco por cento) sobre o valor do bem (tabela FIPE), diretamente à oficina, a ser arcada pelo CONTRATANTE. 
Parágrafo Terceiro: Em nenhuma hipótese, ou seja, de roubo, furto, colisão, incêndio, etc, será devido o pagamento em favor do CONTRATANTE de valores referentes à eventuais LUCROS CESSANTES sofridos. 
11.4 DA CONVERSÃO DA PROMESSA EM COMPROMISSO - No 31º (trigésimo primeiro) dia após o roubo ou furto, não se verificando a localização ou a recuperação, e certificadas por cumpridas as obrigações do CONTRATANTE, o pacto adjeto de promessa de compra sobre documentos poderá se converter em compra e venda com cláusula especial, vinculando CONTRATANTE e CONTRATADA que passam a ser vendedor e comprador, respectivamente. 
11.5 DO LAUDO DE VISTORIA - RESULTADOS - É dever do CONTRATANTE submeter o veículo a uma vistoria antes de requerer a instalação do seu sistema de segurança. Esta vistoria poderá trazer os seguintes resultados: 
A – APROVADO: nesta hipótese o veículo estará liberado para proceder a instalação do sistema; 
B – APROVADO COM DEPRECIAÇÃO: nesta hipótese a contratação será feita com “COM FATOR DE DEPRECIAÇÃO” anotando-se as avarias do veículo que ensejam sua depreciação (por exemplo: batidas, amassados, chassi remarcado, etc). Neste caso a continuidade da contratação fica facultada a expressa escolha do CONTRATANTE que poderá ou não dar continuidade à contratação. Caso opte por não contratar, os valores antecipadamente pagos serão restituídos. Caso opte por dar seqüência à contratação, estará ciente o CONTRATANTE que na hipótese de venda dos documentos em razão do furto ou roubo do veículo sem a recuperação, esta se fará pelo preço de mercado do bem, deduzido o fator de depreciação, até o limite do valor contratualmente fixado. 
C – RECUSADO: a recusa da CONTRATADA, em face de se verificar que o veículo guarda irregularidade que não permite a instalação do sistema de proteção veicular ou irregularidade documental que impeça a venda dos documentos do veículo. 
Parágrafo Único: Quando for aplicado fator de depreciação em razão do estado geral de conservação do veículo, por exemplo, mas não se limitando a amassados na lataria, ferrugem, partes quebradas ou ausentes, poderá o CONTRATANTE optar por regularizar os referidos apontamentos e, sanados, submeter o veículo a nova vistoria, que será paga, nos termos do previsto no item 4. 
11.6 DA OBRIGAÇÃO DE ENTREGA DOS DOCUMENTOS - Ajustada a venda sobre equipamentos do veículo o CONTRATANTE, ora vendedor deverá entregar à CONTRATADA, ora compradora, os seguintes documentos: 
A - Comprovante de quitação das obrigações pecuniárias, bem como das demais obrigações com a CONTRATADA (vistoria, testes e habilitação). 
B - Comprovante de quitação das parcelas vincendas relativas à aquisição do Sistema, quando não utilizado um agente financeiro; 
C - Boletim de Ocorrência; 
D - Formulário de descrição do furto ou roubo, preferencialmente escrito de próprio punho pelo CONTRATANTE ou usuário do veículo na data. 
E - Original do Certificado de Registro e Licenciamento do Veículo (CRLV) (“documento de porte obrigatório”), REGULARIZADO, apto a permitir transferência da propriedade, sem qualquer ressalva ou pendência financeira; 
F - Documento Único de Transferência (“DUT”) assinado pelo CONTRATANTE ou proprietário do veículo, com firma reconhecida por verdadeira, transferindo a propriedade do veículo para a CONTRATADA ou para quem esta indicar; 
G - Na falta do DUT: original da Declaração de Extravio do DUT, endereçada ao órgão de trânsito competente [no caso do Estado de São Paulo, o DEPARTAMENTO ESTADUAL DE TRÂNSITO DE SÃO PAULO (“DETRANSP”)], com firma reconhecida por verdadeira, bem como procuração outorgada pelo proprietário do veículo à CONTRATADA, com poderes específicos para, em nome do outorgante, comparecer aos órgãos de trânsito ou a qualquer outra repartição pública ou particular para regularizar a condição do veículo, com firma reconhecida, por verdadeira e cópia autenticada do RG, CPF/MF e comprovante de residência do CONTRATANTE ou proprietário do veículo; 
G.1 Caso o DUT esteja preenchido em nome do CONTRATANTE: Declaração de Endosso Indevido, com a firma reconhecida por verdadeira, e DUT assinado, com firma reconhecida por verdadeira. 
G.2 Caso o DUT esteja preenchido em nome de pessoa diversa do CONTRATANTE e da CONTRATADA: Procuração outorgada por referida pessoa à CONTRATADA, com poderes específicos, com firma reconhecida por verdadeira e cópia autenticada de RG, CPF/MF e comprovante de residência deste; 
H - Demonstrativo de Débitos perante os órgãos de trânsito competentes até a data do furto/roubo (por meio da emissão de certidão oficial, sendo inaceitável a mera impressão de consulta pela internet), bem como Termo de Responsabilidade por Multas, com firma reconhecida; 
I - IPVA referente ao exercício anterior, até a data do furto/roubo, sendo aceitável o "nada consta de débitos" desde que acompanhado de comprovante do exercício anual; 
J - No caso de veículos adquiridos pelo CONTRATANTE e/ou pelo proprietário por meio de financiamento, documento comprovando a quitação do referido contrato de financiamento, com firma reconhecida, ou Carta de Débito, quando não estiver quitado, para que a CONTRATADA avalie a possibilidade de antecipar o valor devido ao agente financeiro. 
J.1 - Caso o valor devido pelo CONTRATANTE seja menor que o crédito que tem a receber, a diferença a maior lhe será paga após a finalização da avença; caso o valor devido pelo CONTRATANTE seja maior que o crédito, este deverá integralizar a parte faltante, sem que isso ocorra, o capital ficará reservado com a CONTRATADA até que o CONTRATANTE liquide com sua parte. 
K - Chave original e reserva do veículo em caso de furto, ou chave reserva, em caso de roubo; 
L - Cópia do RG e CPF/MF e da CNH do CONTRATANTE e do condutor na data do furto ou roubo; 
M - Certidão de não localização do veículo expedida pelo órgão de trânsito competente ou pela polícia civil. 
Parágrafo Primeiro - A aquisição de sistemas de proteção veicular operados pela CONTRATADA pode ser feito por pessoa não habilitada, todavia, é obrigatório que o condutor na data do furto ou roubo seja habilitado, pois esta condição decorre de lei e seu descumprimento constitui culpa do CONTRATANTE, exonerando a CONTRATADA das obrigações decorrentes do pacto. 
Parágrafo Segundo - É obrigatória a regularização dos documentos do veículo pelo CONTRATANTE, pois somente assim, os mesmos serão recebidos pela CONTRATADA que, por sua vez, em razão do pacto, adquirirá os direitos deles decorrentes. 
11.7 DO PREÇO E DO PAGAMENTO - A CONTRATADA, ora compradora, pagará ao CONTRATANTE, ora vendedor, pelos documentos de seu veículo o preço de mercado do bem, sem qualquer benfeitoria ou acessório, tomando-se por base a tabela FIPE, e na sua falta, a tabela que a substituir, respeitando-se sempre os seguintes limites máximos: 
(i) R$150.000,00 (cento e cinquenta mil) para todos os demais veículos automotores; e (ii) R$ 15.000,00 (quinze mil reais) para veículos com mais de 30 (trinta) anos de fabricação, incluindo, mas não se limitando a: veículos que não tenham valores regulados por tabelas, veículos de colecionador ou veículos para uso “off road” como jipes. 
11.7.1 DO FATOR DE DEPRECIAÇÃO APÓS A VISTORIA – Após a vistoria do veículo e dos respectivos documentos, poderá haver uma depreciação no valor de mercado do bem em razão de, por exemplo, o veículo possuir avarias, ou ter o chassi remarcado, ou, por qualquer outra razão que lhe possa diminuir o valor. Nesta hipótese, fica facultado ao CONTRATANTE aceitar o fator de depreciação e dar continuidade à contratação, permitindo a instalação do sistema ou, não concordando, assinar termo não concordância, situação que ensejará a rescisão do presente contrato e a restituição das quantias eventualmente pagas, nos termos previstos neste contrato. 
11.7.2 O fator depreciação será aplicado sobre o valor de mercado do bem na data do evento furto ou roubo, não modificando os limites estabelecidos na cláusula 11.7, as quais serão sempre os limites máximos estabelecidos para o cumprimento do pacto adjeto de venda sobre documentos. 
11.8 DO PAGAMENTO PROPORCIONAL – FATOR DEPRECIAÇÃO – Conforme previsto neste contrato, havendo a contratação com aceitação do “fator de depreciação”, este será aplicado sobre o valor de mercado do bem, de acordo com a tabela eleita por este contrato, vigente no mês da consumação do evento furto ou roubo. A aplicação do fator de depreciação não altera os limites de pagamento previstos na cláusula 11.7, mas altera o valor de mercado do veículo que será minorado em decorrência da depreciação. Eventuais débitos do veículo (como, por exemplo, multas, licenciamento, IPVA) deverão ser quitados pelo CONTRATANTE, sendo facultado à CONTRATADA permitir o eventual desconto (compensação) de tais débitos no crédito apurado após depreciação, nos termos do presente contrato. 11.09 DO PRAZO PARA PAGAMENTO - O prazo para pagamento é de 30 (trinta) dias após a entrega de todos os documentos obrigatórios, os quais somente serão recebidos a partir do 31º (trigésimo primeiro) dia do roubo, furto, colisão ou incêndio no bem e com perda de mais de 75% (setenta e cinco por cento) do bem. Sem que haja a entrega de todos os documentos não se computará o presente prazo, o qual somente passará a correr quando da entrega efetiva de todos os documentos exigidos. 
11.10 DO INDÍCIO DE FRAUDE - Havendo indícios de fraude ou de prática de atos dolosos por parte do CONTRATANTE na perda do veículo monitorado, ou verificado o descumprimento das demais condições deste Contrato, o pacto adjeto de promessa de compra sobre equipamentos perderá sua eficácia, desobrigando a CONTRATADA. 
12. DISPOSIÇÕES GERAIS 
12.1 RESCISÃO IMOTIVADA 12.1.a - A rescisão será considerada imotivada quando não se fundamentar nas disposições previstas nos artigos 18 (vícios de funcionamento do produto); 20 (vícios de funcionamento dos serviços); 35 (em desacordo com a oferta) e 49 (fora do prazo legal) do Código de Defesa do Consumidor. 
12.1.b - Na hipótese de rescisão imotivada pelo CONTRATANTE, todas as parcelas pagas, seja pela aquisição do Sistema ou pela contratação do serviço, não serão restituídas pela CONTRATADA. No caso de existirem parcelas vincendas com relação à compra do Sistema, a CONTRATANTE deverá pagar à CONTRATADA multa no valor de 10% (dez por cento) sobre o total das parcelas vincendas. A CONTRATANTE deverá entregar o Sistema à CONTRATADA, a qual deverá devolver à CONTRATANTE os cheques referentes às parcelas vincendas, de acordo com datas que ficarem estipuladas administrativa ou judicialmente. 
12.1.c - Na hipótese de rescisão imotivada pela CONTRATADA, o valor pago pelo CONTRATANTE com relação ao Sistema será reembolsado pela CONTRATADA, mediante devolução de todos os componentes do Sistema pelo CONTRATANTE mantendo-se as demais disposições quanto aos prazos. Existindo pagamento antecipado de serviços estes também serão reembolsados proporcionalmente. 
12.1.d – Caso algum componente não tenha sido entregue pela CONTRATANTE à CONTRATADA, o CONTRATANTE deverá pagar à CONTRATADA o valor referente ao componente faltante, de acordo com os preços constantes da tabela vigente à época. 
12.2 RESCISÃO IMOTIVADA DE COMPRA FINANCIADA 
12.2.a - O CONTRATANTE que adquirir o Sistema (produto + habilitação) ou o serviço (mensal) por meio de compra financiada, será responsável, em caso de rescisão imotivada, também pelas despesas relacionadas à rescisão do contrato de financiamento. O valor de referidas despesas será sempre informado à CONTRATADA pela empresa financeira na data do pedido de rescisão do contrato de financiamento. O valor referente a estas despesas deverá ser pago pelo CONTRATANTE conjuntamente com a multa contratual. Quitados referidos débitos este Contrato será considerado rescindido. Caso o CONTRATANTE não pague quaisquer dos débitos, a CONTRATADA se exonera de seus deveres previstos neste Contrato e poderá a qualquer tempo tomar as medidas judiciais cabíveis para recuperar os valores acima mencionados. 
12.2.b - O prazo de devolução dos cheques emitidos pelo ou em favor do CONTRATANTE, eventualmente não compensados e que forem devidos em face da rescisão contratual, é fixado pela Instituição Financeira e ocorrerá sempre e somente, após a regular rescisão deste Contrato. O CONTRANTE sempre deverá obedecer a forma e o prazo fixado na cláusula 10.4, sendo certo ainda que referido prazo não inclui o prazo mencionado na presente cláusula. 
12.2.c - O CONTRATANTE, desde já, autoriza a CONTRATADA a compensar cheques relativos às parcelas vincendas com o valor devido a título de multa, bem como àqueles valores relativos aos componentes faltantes do Kit no momento da devolução do Sistema, e também, eventuais despesas decorrentes da rescisão do contrato de financiamento. 
12.3 O CONTRATANTE ficará obrigado a pagar a taxa de retirada/desinstalação do Sistema, conforme os preços constantes da tabela vigente à época. 
12.4 O descumprimento de qualquer disposição deste Contrato pela CONTRATANTE autorizará a CONTRATADA a suspender imediatamente a prestação de serviço, independentemente de prévia comunicação, notificação ou interpelação judicial ou extrajudicial e sem que qualquer direito à indenização assista o CONTRATANTE. 
12.5 A nulidade ou ineficácia de qualquer das cláusulas contidas neste instrumento não invalidará as demais disposições contratuais, as quais permanecerão em pleno vigor. 
12.6 O CONTRATANTE declara estar devidamente instruído pela CONTRATADA quanto à forma e condições de utilização do Sistema, bem como declara que tomou conhecimento prévio do inteiro teor deste instrumento. Declara, ainda, que foi orientado sobre a possibilidade de rescindir este instrumento, em até sete dias, contados da data da assinatura sem qualquer ônus, os exatos termos do artigo 49 da Lei 8.078/90. 
12.7 DA PREFERENCIA DE COMPRA PELO CONTRATANTE EM CASO DE RECUPERAÇÃO DO BEM APÓS A VENDA SOBRE EQUIPAMENTO - As partes ajustam que na hipótese da recuperação do veículo monitorado, dentro do período de 12 (doze) meses contados a partir da efetivação da venda sobre equipamentos, a CONTRATADA, na condição de nova proprietária do veículo, notificará, por escrito, o CONTRATANTE acerca da recuperação e da faculdade deste optar pela aquisição do veículo, restituindo à CONTRATADA os valores recebidos, monetariamente corrigidos. 
12.8 COMO EXPRESSAMENTE DECLARADO NA CLÁUSULA 1.7 DESTE CONTRATO, O SISTEMA DE SEGURANCA OPERADO PELA CONTRATADA E O PACTO ADJETO DE VENDA SOBRE DOCUMENTOS NÃO É E NÃO EQUIVALE A UM CONTRATO DE SEGURO, E, PORTANTO, NÃO HÁ COBERTURA DE ROUBO OU FURTO PARCIAL (PARTES DO PRÓPRIO VEÍCULO OU SEUS ACESSÓRIOS), NÃO HÁ AVALIACAO DE RISCO, NÃO SE ESTABELECE PRÊMIO, NÃO HÁ BÔNUS DE QUALQUER ESPÉCIE E NEM SE INDENIZA TERCEIROS. 
12.9 O CONTRATANTE autoriza a CONTRATADA a utilizar-se do envio de e-mails, sms, mms, torpedos, para oferecer-lhe produtos, serviços ou vantagens que irá disponibilizar no mercado de consumo, bem como, para lembrá-lo de seus deveres contratuais de testes, pagamento em dia, vistorias, habilitação, sempre objetivando aprimorar a relação entre as partes. 
13 – DA GARANTIA DO SISTEMA E DA ASSISTÊNCIA TÉCNICA 
13.1 A GARANTIA do sistema RASTREADOR é vinculada ao tempo de vigência do presente contrato. Assim, será considerada permanente, desde que o contrato esteja em plena vigência. Findo o prazo de vigência contratual, finda está a cobertura da garantia. Caso haja uma nova contratação, renovar-se-á a vigência da garantia. 
13.2 No curso do prazo contratual, estando o CONTRATANTE adimplente com seus deveres financeiros, não haverá qualquer cobrança para reparo de vícios no sistema rastreador, desde que decorrentes de problemas técnicos de software (comunicação de sistema) ou de harduare (produto propriamente dito) sendo certo que sempre que se observar a ocorrência de vícios, o sistema será substituído por outro, em perfeito estado de funcionamento. 
13.3 Se houver problemas (vícios de funcionamento) com o sistema rastreador causados por uso inadequado por parte do CONTRATANTE (como por exemplo, mas não se limitando a: enchentes, intervenção feita por terceiros não credenciados ou autorizados da CONTRATADA) HAVERÁ COBRANÇA da mão-de-obra para a troca do sistema por outro em perfeito estado de funcionamento, bem como, haverá a cobrança de um novo sistema rastreador, ao preço praticado na data da substituição. 
13.4 A assistência técnica será prestada pela CONTRATADA em favor do CONTRATANTE em dias úteis, no horário comercial, através de técnicos credenciados, ou de bases fixas credenciadas ou autorizadas pela CONTRATADA mediante solicitação do CONTRATANTE. A CONTRATADA sempre informará previamente ao CONTRATANTE a existência de eventual custo, através de orçamento prévio que deverá ser expressamente aprovado, quando os serviços solicitados ou os reparos necessários não estiverem cobertos pela garantia. 
13.5 Poderá haver atendimentos especiais (fora do horário comercial e sem prévio agendamento para atendimento) sempre que os vícios do sistema impossibilitarem o uso do veículo. Nestas circunstancias o CONTRATANTE deverá solicitar à CONTRATADA o atendimento e a respectiva assistência técnica, a qual se dera pelo atendimento de um técnico no local onde estiver o veículo. Para estes casos, será fixado um tempo de espera, dentro do qual o técnico chegará até o local, não se computando neste prazo, o prazo necessário para o reparo no sistema. 
13.6 Havendo circunstâncias que impeçam o atendimento (como por exemplo enchentes), fica o CONTRATANTE ciente que o atendimento se dará dentro do menor intervalo de tempo possível após cessadas as circunstâncias que impeçam o atendimento técnico de se deslocar para o local no qual encontra-se o veículo. 
13.7 O técnico da CONTRATADA ao prestar assistência técnica verificará se o problema é efetivamente do sistema de rastreamento ou decorre de algum problema com o veículo. Se constatado que não se trata de problema com o sistema de rastreamento, entregará para o CONTRATANTE um check list de assistência técnica que deverá ser assinado por este, encerrando a ordem de serviços. 

14. DA SUBSTITUIÇÃO ONEROSA DO SISTEMA DE RASTREAMENTO EM FACE DA OCORRÊNCIA DE FURTO OU ROUBO 14.1 Nas hipóteses de furto ou roubo do veículo sem a respectiva recuperação do veículo, pacto adjeto de venda sobre documentos não dá ao CONTRATANTE o direito de receber outro sistema gratuitamente, de forma que, havendo a aquisição de um novo veículo e uma nova contratação, caberá ao CONTRATANTE adquirir um novo sistema e firmar um novo contrato de prestação de serviços. 
14.2 Havendo o furto ou roubo do veículo e a respectiva recuperação, se na vistoria decorrente da recuperação se verificar que o sistema de rastreamento foi subtraído parcial ou integralmente ou, ainda, que o mesmo sofreu dano ou violação que não permite reparo, sua substituição integral ou parcial (se cabível) será onerosa, de forma que, caberá ao CONTRATANTE pagar pelo novo produto, ou por partes do kit que será instalado em seu veículo recuperado. 
15 – DO REGISTRO DO CONTRATO – DISPONIBILIDADE DE ENTREGA – DA PUBLICIDADE E SUAS CLÁUSULAS E CONDIÇÕES 
15.1 A CONTRATADA declara que este contrato encontra-se registrado devidamente junto ao 8° Cartório de Notas da Capital do Estado de São Paulo e a sua íntegra em versão impressa, para consulta, pode ser adquirido, gratuitamente, na sede da CONTRATADA ou envio por e-mail. 
15.2 Em razão do registro deste contrato (o que o torna público), bem como, em razão de o mesmo encontrar-se disponível para acesso e consulta, não se admitirá a alegação de desconhecimento das suas cláusulas e das obrigações delas decorrentes por qualquer das partes, estando cumpridos pela CONTRATADA todos os deveres atinentes à informação clara, precisa, ostensiva e em linguagem de fácil entendimento exigidas pela Lei n° 8.078/90 (Código de Defesa do Consumidor). 
16. DO FORO As partes elegem o Foro do domicílio do CONTRATANTE para dirimir quaisquer controvérsias oriundas do presente Contrato. E por estarem assim justas e contratadas, as partes obrigam-se ao integral cumprimento do presente instrumento, assinandoo em 2 (duas) vias de igual teor e forma, na presença de duas testemunhas.

____________________________________________________________________________

CONTRATANTE (assinatura igual cheque/documento)

NELSON SCHINDLER


____________________________________________ ________________________________

Local e data

PROTEGE FACIL PROTEÇÃO E RECUPERAÇÃO DE VEICULOS LTDA


Testemunhas: 1._________________________________ 
Testemunhas: 2. _________________________________
    </body>
</html>
